### ISSUE TITLE
Delegate SQLAlchemy

### ISSUE THREAD

**Issue by fantix** [fantix/gino#10]
Should GINO ever do that?

It will be as simple as a few import delegates, instead of:

```python
from sqlalchemy import Column
# id = Column(...
```

you can:

```python
from gino import Gino
db = Gino()
# id = db.Column(...
```

**Comment by wwwjfy** [comment]
+1, so we can hide sqlalchemy from users

**Comment by fantix** [comment]
Fair enough. Delegate also those types in `sqlalchemy.dialects.postgresql` - `JSONB` for example.
