### ISSUE TITLE
Front Page example will fail to run, as the Table is not generated. Add generator file to run

### ISSUE THREAD

**Issue by Kentoseth** [fantix/gino#103]
* GINO version: gino (0.5.5)
* Python version: 3.6.2
* Operating System: Ubuntu

### Description

The frontpage/readme.md example will fail, as the beginner type of user will be unaware that the `users` table is not being generated for them.

It would be useful to add a Table/DB generator file written in `sqlalchemy` so that the generating can occur.

### What I Did

Ran basic example and had to figure out how to generate Table from examples.

**Comment by fantix** [comment]
Yeah you're probably right about that. I'll update.

**Comment by Kentoseth** [comment]
I have an experimental file that you might be able to use:

```
import sqlalchemy as sa
from gino import Gino

db = Gino()

class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.BigInteger(), primary_key=True)
    nickname = db.Column(db.Unicode())

db_endpoint = 'postgres://postgres@localhost/dbname'
db_engine = sa.create_engine(db_endpoint)
db.create_all(bind=db_engine)
db_engine.dispose()
```

Although it would also be quite helpful to have a working example showing the following:

 1. Create database function (in maybe `db_generator.py`)
 2. Read, Create, Update, Delete functions ( `db.py`)
 3. Calling these `async` functions from 2) in the app (`app.py`)
 4. Showing how to make it all work together (which many async-postgres libs lack)

I've got it to (mostly) work myself, but my solution may be a bit hack-like to present as a full tutorial.

**Comment by fantix** [comment]
Thanks for the supplement! It might also be useful to mention #28 here.

**Comment by fantix** [comment]
Front Page example is now working on empty database, closing this now.
