### ISSUE TITLE
Log SQL statements

### ISSUE THREAD

**Issue by Dodobibi** [fantix/gino#142]
* GINO version: 0.6
* Python version: 3.6
* Operating System: Linux

### Description

Is there a way to log SQL statements ?
The parameter _echo_ is not accepted, not implemented in _create_engine_

**Comment by fantix** [comment]
Guess you meant GINO 0.6 in branch t59_2? On PyPI the latest version is 0.5.8. It will be an accepted parameter in 0.6 (I'll add it a bit later), but it won't happen for 0.5.x.

**Comment by Dodobibi** [comment]
Yes, in t59_2 branch, the echo parameters in not accepted again.
(Excuse my English, I'm French)

**Comment by fantix** [comment]
No worries, non-native English speaker too 😈  I'll add it soon, and the progress shall be tracked in this issue. Please feel free to let me know if anything else is missing or wanted.
