### ISSUE TITLE
__declare_last__ sqlalchemy mixin doesn't work

### ISSUE THREAD

**Issue by reefactor** [fantix/gino#147]
* GINO version: 0.5.5
* Python version: 3.6.2
* Operating System: ubuntu

### Description

Adding timestamping updates with sqlalchemy mixin __declare_last__() (http://docs.sqlalchemy.org/en/latest/orm/extensions/declarative/api.html#declare-last)

### What I Did

My approach is based on simple recipe https://til.tafkas.net/post/python/auto-timestamping-sqlalchemy-entities/

To simplify example, I've added `assert False` to ensure that expected handler __declare_last__() is not called by sqlalchemy. 
Code with snippet below must crash, yet it doesn't
```
import datetime
import sqlalchemy
import gino

class TimeStampMixin(object):
    @staticmethod
    def _modified_at_time(mapper, connection, target):
        assert False  # force fall here
        target.modified_at = datetime.datetime.utcnow()

    @classmethod
    def __declare_last__(cls):
        assert False  # force fall here
        sqlalchemy.event.listen(cls, 'before_update', cls._modified_at_time)


db = gino.Gino()

class User(TimeStampMixin, db.Model):
    modified_at = Column(DateTime, nullable=True, default=datetime.datetime.utcnow)
```

I also tried putting `TimeStampMixin` into global base class, but also no luck:
```
db = gino.Gino(model_classes=gino.Gino.model_base_classes + (TimeStampMixin, ))
```

Any suggestions on how I'm doing it wrong?
How can I achieve same goal with different approach?
Thanks.

**Comment by fantix** [comment]
`__declare_last__` is a feature of SQLAlchemy ORM, not core, so it is by default not in GINO. Let me check in detail how it should be.

**Comment by fantix** [comment]
The ultimate solution is of course using a database trigger as described here: https://stackoverflow.com/a/8745713/3316267

Solving this issue in GINO would require copying over the event system from SQLAlchemy. Now that triggers can still workaround this issue, unless there're further urgent need on this event feature (please open a new feature request), guess this feature won't be landing early than v0.7. Please feel free to let me know if you have other questions on this.

**Comment by reefactor** [comment]
Thanks for quick response. 
Events feature would be nice to have, but not urgent.
Keep GINO simple and light.

**Comment by fantix** [comment]
Sure thing 😃

**Comment by reefactor** [comment]
one last question: is it ok to hook (via same mixin class) either `update(**kwargs)` or `_update(**kwargs)` method of CRUDModel? Have you considered valid ways to hook GINO ORM CRUD operations?

**Comment by fantix** [comment]
Yeah it is something like this:

```python
import asyncio
from datetime import datetime

from gino import Gino
from gino.crud import CRUDModel, UpdateRequest, DEFAULT


class HookedUpdateRequest(UpdateRequest):
    async def apply(self, bind=None, timeout=DEFAULT):
        self.update(last_modified=datetime.utcnow())
        return await super().apply(bind, timeout)


class HookedCRUDModel(CRUDModel):
    def _update(self, **values):
        return HookedUpdateRequest(self).update(**values)


db = Gino(model_classes=(HookedCRUDModel,))


class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.BigInteger(), primary_key=True)
    nickname = db.Column(db.Unicode(), default='noname')
    profile = db.Column(db.JSONB())
    last_modified = db.Column(db.DateTime())

    def __repr__(self):
        return '{}<{}> @ {}'.format(self.nickname, self.id, self.last_modified)


async def main():
    await db.create_engine('asyncpg://localhost/gino')

    await db.gino.drop_all()
    await db.gino.create_all()

    u = await User.create(nickname='fantix')
    print(u)

    await u.update(nickname='daisy').apply()
    print(u)

    await asyncio.sleep(1)

    await u.update(nickname='fantix').apply()
    print(u)


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

But it is just too narrow - only through the `update().apply()` can `last_modified` be automatically updated. Anyway, might be useful in some cases 😸

**Comment by reefactor** [comment]
cool, thanks again

**Comment by fantix** [comment]
any time
