### ISSUE TITLE
I don't understand the name... you say it is not ORM but also say it is ORM

### ISSUE THREAD

**Issue by kootenpv** [fantix/gino#159]
"GINO Is Not ORM - a Python asyncio ORM on SQLAlchemy core."

**Comment by fantix** [comment]
Oh I must have explained this somewhere, it is missing from README now ~ let me add it back.

So GINO does perform the Object-Relational mapping work under the [Data Mapper Pattern](https://en.wikipedia.org/wiki/Data_mapper_pattern), but it is just not a *traditional* ORM. The Objects in GINO are completely stateless from database - they are pure plain Python objects in memory. Changing their attribute values does not make them "dirty" - or in a different way of thinking they are always "dirty". Any access to database must be explicitly executed. Using GINO is more like making up SQL clauses with Models and Objects, executing them to make changes in database, or loading data from database and wraping the results with Objects again. Objects are just row data containers, you are still dealing with SQL which is represented by Models and SQLAlchemy core grammars.

So far GINO has no model relationship or inheritance support, only very basic CRUD operations (of course it is possible to make complex join queries with GINO models, you just need to do it yourself, and the result cannot yet be mapped into a list of Objects, each has a collection of some related Objects or something traditional ORM does). This simplicity also contributes to the "not ORM" part.

I think simplicity and explicitness are actually good in the context of the already-very-complex asynchronous environment. There's less chance to hold up transactions while waiting for a non-db long polling for example, making the risk of db deadlock lower.

**Comment by fantix** [comment]
Oh by the way, you can ignore the ORM part of GINO and only use it as an asynchronous version of SQLAlchemy core, like SQLAlchemy itself.
