### ISSUE TITLE
Any options for admin panel? 

### ISSUE THREAD

**Issue by bnopne** [fantix/gino#167]
Are there any options of auto-generated admin panel for `gino` models? I tried to use `gino` models on `Flask-admin`, but had no luck with it (`_sa_instance_state_manager` attribute was missing).

**Comment by fantix** [comment]
Oh yes, we used Flask-Admin in one of our project with GINO. Let me share the code, one sec.

**Comment by bnopne** [comment]
Thanks a lot, Dear Sir, may The Force be with you!

**Comment by fantix** [comment]
Quite welcome you are. 😸

**Comment by xnuinside** [comment]
Maybe will be useful for someone: https://github.com/xnuinside/gino_admin

**Comment by fantix** [comment]
@xnuinside thanks for using and sharing! This is now added on https://python-gino.org/credits/

refs #260, https://github.com/python-gino/python-gino.org/commit/f45fe7fd2bd58285438281dcdbbeef8787661207
