### ISSUE TITLE
mixins do not work

### ISSUE THREAD

**Issue by aglassdarkly** [fantix/gino#174]
* GINO version: 0.6.1
* Python version: 3.6.0
* Operating System: ubuntu 17.10

### Description

I want to use a simple mixin to add common columns.
The added columns did not resolve to values after a query. 

### What I Did
```
import asyncio

from gino import Gino

db = Gino()


class Audit:
    created = db.Column(db.DateTime(timezone=True))


class Thing(Audit, db.Model):
    __tablename__ = 'thing'

    id = db.Column(db.Integer, primary_key=True)


async def main():
    async with db.with_bind('postgresql://user:password@localhost:5432/db'):
        await Thing.create(id='splunge')
        thing = await Thing.query.where(Thing.id == 'splunge').gino.first()
        print('name: {} created: {}'.format(thing.id, thing.created))


if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

output:

> name: splunge created: (no name)

Accessing the created attribute returns a Column instance, not the value associated with the column.

**Comment by fantix** [comment]
Oh yes, I've ran into the same issue. Sorry for the inconvenience! I'll have it fixed in 0.6.2.
