### ISSUE TITLE
Upgrading from 0.5.8 to 0.6.2 seems to break where() in at least certain cases

### ISSUE THREAD

**Issue by kinware** [fantix/gino#175]
* GINO version: 0.6.2
* Python version: 3.6.3
* Operating System: Linux

### Description

Attempting to upgrade from Gino 0.5.8 to 0.6.2 appears to cause WHERE clauses to become incomplete when using boolean operators in where() argument.

### What I Did

```
res = await SomeModel.update.values(
    status='error'
).where(
    (SomeModel.someField == 'someValue') and 
    (SomeModel.id == 5)      # <-- This is missing from SQL WHERE clause
).gino.status()
```

The above code works under Gino 0.5.8 but appears to break on 0.6.2. What happens in 0.6.2 is that the second part of the SQL WHERE clause (filtering on 'SomeModel.id' ) will be omitted in the query. In this case this causes all rows matching the first condition (someField == 'someValue') to be updated - not just the single row where the id equals 5.

**Comment by fantix** [comment]
You should use `db.and_` [(doc)](http://docs.sqlalchemy.org/en/latest/core/sqlelement.html?highlight=and_#sqlalchemy.sql.expression.and_) instead of Python `and`, or simply use two chaining `where`:

```python
res = await SomeModel.update.values(
    status='error'
).where(
    SomeModel.someField == 'someValue'
).where(
    SomeModel.id == 5
).gino.status()
```

Because Python `and` will simply return the first expression if it evaluates to a `True` value. Looks like it shouldn't work for 0.5 too, let me check the reason.

**Comment by kinware** [comment]
Thanks for quick answer fantix!

You are completely right - I'm using the wrong syntax. I tested again, and I can't reproduce the problem.

Switching from "and" to "&" does the trick too, just as using and_() does.

Sorry for the confusion. Closing issue.

**Comment by fantix** [comment]
Ah yes, `&` is good, thanks for amending 😄  also use `column.is_(None)` instead of `column is None`, just a reminder

**Comment by kinware** [comment]
I looked through it once more, and I've determined it was a simultaneous refactoring in my code that caused me to incorrectly assume that the problem was with Gino, when in fact it was my incorrect use of the python 'and' operator in Gino/SQLAlchemy. Thanks for the help!

**Comment by fantix** [comment]
Any time! Hope your data is not ruined!

**Comment by kinware** [comment]
No worries, just playing around :)
