### ISSUE TITLE
Support Python 3.5

### ISSUE THREAD

**Issue by tpraizler** [fantix/gino#187]
* GINO version: 0.6.2
* Python version: 3.5.3
* Operating System:

### Description
Is Python3.5 supported?

**Comment by fantix** [comment]
Not yet, but we could have it later I think.

**Comment by tpraizler** [comment]
I see, well, I would really like to use this project, but I use python 3.5.3..:-|
Do you have an estimation on when this might be available?

**Comment by fantix** [comment]
Let me try to include this in the coming v0.7, should be a week away or so.

**Comment by tpraizler** [comment]
oh! That's awesome! Thanks!

**Comment by tpraizler** [comment]
Hey @fantix when do you plan to release version 0.7? I really want to start using this project.

**Comment by wwwjfy** [comment]
Hi @tpraizler, I don't know what @fantix has in mind for 0.7, but if you don't want to use current HEAD as a dependency, I can help to release a patch version. I'll do it tomorrow evening if he doesn't respond.

**Comment by tpraizler** [comment]
@wwwjfy That will be great!

**Comment by fantix** [comment]
Yeah thanks @wwwjfy please do so! I’m on my way back home, should be able to get online tomorrow.

**Comment by wwwjfy** [comment]
pushed the version bump commit/tag, but still need to update PyPI. @fantix feel free to amend/remove my commit.

**Comment by wwwjfy** [comment]
I don't know how PyPI works but 0.6.4 is there. @tpraizler 
@fantix did you upload it manually or PyPI could fetch updates from Github?

**Comment by fantix** [comment]
@wwwjfy oh it must be the auto build script ran by Travis

**Comment by wwwjfy** [comment]
Cool, didn't know Travis can do that.
