### ISSUE TITLE
improve CRUDModel.get() for composite primary keys

### ISSUE THREAD

**Issue by aglassdarkly** [fantix/gino#192]
* GINO version: 0.6.2
* Python version: 3.6.3
* Operating System: Ubuntu 17.10

### Description

CRUDModel.get() is very useful but handling composite primary keys is awkward. The comment for the ident param states: 
> For composite primary keys this should be a tuple of values for all keys in database order.

Database order is a fragile concept. For instance, suppose I have composite primary key (firstname, lastname). Both are strings. I use model.get((first, last)) in my code in many places. Then the key changes to (lastname, firstname), perhaps for performance concerns or perhaps accidentally, such as changing the order of variables in the SQLAlchemy model. The uses of get() will now all be wrong, but because both columns are of the same type no exceptions will be raised and the results may not be obvious.

Ideally get() would accept kwargs to specify composite keys, but this would conflict with the existing params. Perhaps accepting a dict for ident would suffice and still be fully backwards compatible.

**Comment by fantix** [comment]
I think it is a fair point, any idea @wwwjfy ?

**Comment by wwwjfy** [comment]
Though it's rare in the real world AFAIK because changing the order of the primary key has no obvious advantages except readability (I'm not a DBA, correct me if I'm wrong), I think it's fine to support dict.
I agree with @aglassdarkly to not use kwargs.
