### ISSUE TITLE
Asyncio.gather concurent requesting

### ISSUE THREAD

**Issue by se4rch3r** [fantix/gino#218]
* Gino version: 0.7.0
* Python version: 3.6.3
* Operating System: Ubuntu 17.10

### Description:
I want to make request in two coroutines at one time.

### What I Did
```
db = Gino()

... declarative description ...

async def coro():
    result = await await Model.query.where(field == value).gino.all()

loop = asyncio.get_event_loop()
loop.run_until_complete(asyncio.gather(coro(), coro()))
```

And fails with:

```
...
 File "/home/user/PycharmProjects/eterw2x-v2/venv/lib/python3.6/site-packages/asyncpg/pool.py", line 520, in release
    _release_impl(connection._holder, timeout), loop=self._loop)
  File "/home/user/PycharmProjects/eterw2x-v2/venv/lib/python3.6/site-packages/asyncpg/pool.py", line 493, in _release_impl
    await ch.release(timeout)
  File "/home/user/PycharmProjects/eterw2x-v2/venv/lib/python3.6/site-packages/asyncpg/pool.py", line 217, in release
    raise ex
  File "/home/user/PycharmProjects/eterw2x-v2/venv/lib/python3.6/site-packages/asyncpg/pool.py", line 206, in release
    await self._con.reset(timeout=budget)
  File "/home/user/PycharmProjects/eterw2x-v2/venv/lib/python3.6/site-packages/asyncpg/connection.py", line 1034, in reset
    await self.execute(reset_query, timeout=timeout)
  File "/home/user/PycharmProjects/eterw2x-v2/venv/lib/python3.6/site-packages/asyncpg/connection.py", line 238, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 319, in query
  File "asyncpg/protocol/protocol.pyx", line 796, in asyncpg.protocol.protocol.BaseProtocol._dispatch_result
asyncpg.exceptions._base.InternalClientError: got result for unknown protocol state 3

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "<input>", line 3, in forever
  File "/home/user/PycharmProjects/eterw2x-v2/eterw2x/repositories/gino/offsets_repository.py", line 16, in get_offset_by_name
    scheme.ReceiverOffset.offset_name, offset_name)
  File "/home/user/PycharmProjects/eterw2x-v2/eterw2x/repositories/gino/gino_repository.py", line 34, in get
    result = await query.gino.all()
  File "/home/user/PycharmProjects/eterw2x-v2/venv/lib/python3.6/site-packages/gino/api.py", line 183, in __aexit__
    await self._args[0].pop_bind().close()
AttributeError: 'NoneType' object has no attribute 'close'
```

I understand that there is likely no way out.. How can I make "carefree" fix for this?

**Comment by fantix** [comment]
May I take a look at how `with_bind()` is used in your code please? Looks like you are concurrently binding different engines to a single `db` instance. If you do need to concurrently deal with multiple databases with the same set of database schema (one `db` instance), you may check #209 for solution. Or else, I would suggest replace `with_bind()` for each coroutine with `set_bind()` at the beginning before any other coroutines start, and `db.pop_bind().close()` to cleanup when shutting down (or make sure `with_bind()` wraps the whole process lifecycle).

**Comment by se4rch3r** [comment]
Yes, I concurrently binding different engines to a single `db` instance. Small listing from real code:
```
...
        async with scheme.mapper.with_bind(self._database_url):
            query = self._gino_model.query.where(field == value)
            result = await query.gino.all()
        entities = []
        if len(result) == 1:
...
```
This part of code can be called twice from one(and more) coroutine, if that matters.
In this case i can't replace context manager to set_bind?

**Comment by fantix** [comment]
Nope you can't use `set_bind()` here within this piece of code. To make it work, do it like this:

    ...
        engine = await gino.create_engine(self._database_url)
        try:
            query = self._gino_model.query.where(field == value)
            result = await engine.all(query)
        finally:
            await engine.close()
        entities = []
        if len(result) == 1:
    ...

This works the same way as your code but this one should survive concurrency.

However my concern is, do you really need to make new connections *every time* this piece of code runs, and close them afterwards. If it is the same database, you can have a single engine(bind, db pool, connections) shared by all coroutines.

**Comment by fantix** [comment]
Sure thing, see you a bit later. I'll look into the RTD search thing, it's probably caused by recent RTD updates - cache breaks things.

**Comment by se4rch3r** [comment]
I have nothing to report. I create engine and use it in several coroutines, like this:
```
class Storage:
    def __init__(self, engine: Engine):
        self._engine = engine
    
    def method(self, **kwargs):
        return await Model.create(self._engine, **kwargs)

async def main():
    engine = await create_engine('..')
    storage = Storage(engine)
    ...
```
And seems to work with few engines:

```
from project.storages.gino import scheme
import asyncio
import gino


loop = asyncio.get_event_loop()
pool = []

e1 = loop.run_until_complete(gino.create_engine(
    'postgresql://root:toor@127.0.0.1/db
e2 = loop.run_until_complete(gino.create_engine(
    'postgresql://root:toor@127.0.0.1/db'))

async def init(e: gino.engine.Engine):
    q = scheme.Contact.query
    while True:
        pool.append(await e.all(q))
loop.run_until_complete(asyncio.gather(init(e1), init(e2)))
```
Thanks!

**Comment by fantix** [comment]
Okay good to know it is working for you! Please feel free to let me know if you have further questions or issues.
