### ISSUE TITLE
Error creating table with ForeignKey referencing table wo `__tablename__` attribute

### ISSUE THREAD

**Issue by gyermolenko** [fantix/gino#224]
* GINO version: 0.7.2
* Python version: 3.6.5

Trying to create the following declarative schema:
```
class Parent(db.Model):
    id = db.Column(db.Integer, primary_key=True)

class Child(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    parent_id = db.Column(db.Integer, db.ForeignKey('parent.id'))
```

Got this exception:
```
Traceback (most recent call last):
  File "xxx/lib/python3.6/site-packages/gino/declarative.py", line 34, in __getattr__
    raise AttributeError
AttributeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "script.py", line 150, in <module>
    loop.run_until_complete(Parent.create())
  File "/home/xxx/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/home/xxx/lib/python3.6/site-packages/gino/crud.py", line 418, in _create_without_instance
    return await cls(**values)._create(bind=bind, timeout=timeout)
  File "/home/xxx/lib/python3.6/site-packages/gino/crud.py", line 398, in __init__
    self.update(**values)
  File "/home/xxx/lib/python3.6/site-packages/gino/crud.py", line 518, in _update
    return self._update_request_cls(self).update(**values)
  File "/home/xxx/lib/python3.6/site-packages/gino/crud.py", line 81, in __init__
    type(self._instance).update)
  File "/home/xxx/lib/python3.6/site-packages/gino/declarative.py", line 38, in __getattr__
    self.__name__, item))
AttributeError: type object 'Parent' has no attribute 'update'

```

Not reproducible with  `__tablename__` fields:
```
class Parent(db.Model):
     __tablename__ = 'parents'
    id = db.Column(db.Integer, primary_key=True)

class Child(db.Model):
     __tablename__ = 'children'
    id = db.Column(db.Integer, primary_key=True)
    parent_id = db.Column(db.Integer, db.ForeignKey('parents.id'))
```

Not reproducible creating only one table without  `__tablename__` (and no fk to this table):
```
class Parent(db.Model):
    id = db.Column(db.Integer, primary_key=True)
```

**Comment by fantix** [comment]
Ah, thanks for the report and sorry for the confusion! `__tablename__` is a mandatory field to define a valid model. Without `__tablename__`, there will be no SQLAlchemy `Table` created, that's why `Parent.create()` shouldn't work in this case. May I learn about your use case why __tablename__ is not given at declaration?

However tracking your example, `Parent.create()` does fail but for a improper reason (`Parent()` shouldn't fail in this case but it does now. I'll push a commit to fix this).

**Comment by gyermolenko** [comment]
thank you for a quick response. 
I have no particular reason to omit `__tablename__` , just copied some tables from some old projects. 

From user perspective: error was a little bit misleading. 
Also, Is it possible to place a note about this nuance somewhere?

**Comment by gyermolenko** [comment]
And somehow related topic.
What do you think if I update `Showcase` section from readme?
1. I think User-Posts(with fk) example is richer (instead of just User table)
2. When you do `asyncio.get_event_loop().run_until_complete(main())` - it is all-or-nothing operation for all the examples inside `main()`. I mean, it is a little bit inconvenient if I want to run specific command from it.
What do you think about several `loop.run_until_complete` commands that could be run one by one?

**Comment by fantix** [comment]
Yeah I totally agree with you on the error thing, will fix. And the [tutorial](https://python-gino.readthedocs.io/en/latest/tutorial.html) doc does mentioned about `__tablename__` but it is missing from the [schema](https://python-gino.readthedocs.io/en/latest/schema.html) doc, will fix that too.

For the README, 1) yes, richer would be good, however I'd prefer the complexity to be a new section 2) well you know as a showcase I think it would be better to have less lines. Anyway thanks for the suggestion! Also, feel free to send me a PR 😄
