### ISSUE TITLE
exception on get_or_404 when sanic is not installed and db row doesn't exist

### ISSUE THREAD

**Issue by wwwjfy** [fantix/gino#23]
* GINO version: 0.2.1
* Python version: 3.6
* Operating System: Doesn't matter

### Description

The simplest way to reproduce the issue, is to run test_basic.test_get using `get_or_404` instead of `get` with first argument `u1.id + 1`.

The error is `ModuleNotFoundError: No module named 'sanic'`

**Comment by wwwjfy** [comment]
Though `get_or_404` should only be invoked when `sanic` is installed, it's still not good experience to show `ModuleNotFoundError`.

Maybe we can fail early (before db queries) and throw an exception with a proper message to let the user know what happened and what can be done.

**Comment by fantix** [comment]
Or even simply offer no `get_or_404` method if `sanic` is not found. Either okay for me.
