### ISSUE TITLE
Tornado test fails with: Option 'db_port' is required to be a int

### ISSUE THREAD

**Issue by gyermolenko** [fantix/gino#231]
* GINO version: 0.7.3

`$ pytest tests/test_tornado.py` 
fails with
`tornado.options.Error: Option 'db_port' is required to be a int (<class 'str'> given)`

https://github.com/fantix/gino/blob/master/gino/ext/tornado.py#L186
defines `db_port` option as an `int` and test tries to set str.
https://github.com/fantix/gino/blob/master/tests/models.py#L12

Such settings often come from os env (as in this case) and such imports are always strings.
The decision here is a little bit bigger that put one `int(db_port)` somewhere.

**Comment by fantix** [comment]
You are right - it is not just `int(db_port)`. Unfortunately I had to use Tornado internal members because it didn't expose such API.
