### ISSUE TITLE
Coverage report across multiple Python versions

### ISSUE THREAD

**Issue by wwwjfy** [fantix/gino#249]
For #244, I misunderstood how Travis works. It seems py35 and py36 run in different containers, so the combine doesn't actually combine py35 and py36 reports. Maybe who posts later overrides the earlier report. That's why sometimes we get 98% and sometimes 94%.

A few options I can think of:
- only report coverage for py36
- [codecov](https://codecov.io/gh) seems to adopt higher coverage report, as I tested, no matter who reports earlier
- use our own server to combine the coverage report and post to coveralls

**Comment by fantix** [comment]
I think only report coverage for py36 would do, thoughts?

**Comment by wwwjfy** [comment]
+1, will commit later

**Comment by fantix** [comment]
Appreciated!
