### ISSUE TITLE
asyncpg new version support

### ISSUE THREAD

**Issue by Olegt0rr** [fantix/gino#251]
Can't work with GINO on my Mac cause asyncpg has a bug in v0.15.0
Bug was fixed in asyncpg v0.15.0
gino 0.7.3 has requirement asyncpg==0.15.0, asyncpg 0.16.0 is incompatible

Please, add asyncpg v0.16.0 support

**Comment by wwwjfy** [comment]
I just uploaded 0.7.4. It should be available soon.

**Comment by wwwjfy** [comment]
@Olegt0rr 0.7.4 is available on pypi now.

I don't know why travis reported uploading failure (I've tried a few times) but I can see it on pypi 🤔
