### ISSUE TITLE
ModelLoader: return None if all columns are None

### ISSUE THREAD

**Issue by p4l1ly** [fantix/gino#281]
* GINO version: 0.7.4
* Python version: 3.6
* asyncpg version: 0.16.0
* aiocontextvars version: 0.1.2
* PostgreSQL version: 10.3

### Description

Hi, as you do [here](https://github.com/fantix/gino/blob/master/gino/loader.py#L75), I think it would make sense also for non-distinct `ModelLoader` to return `None` if all columns are `None`. This is a breaking change, but it makes sense and SQLAlchemy works like that too.

### What I Did

Use case: I have an outerjoin query and I don't care about distinctness (let's say it is already handled in SQL). The tables are in 99.99% of cases designed in the way that all columns cannot be null. So if all the columns are null in the outerjoin, it means that the record does not exist. It would be therefore convenient to return `None` instead of the model with no data.

```
(
    sqlalchemy.orm.Query([Route.__table__, Status.__table__])
    .outerjoin(Status.__table__)
    .selectable.execution_options(loader=(Route, Status))
)
```

I think it can be done somehow even now with the `distinct` feature, however, for simple use cases, I think it is an overkill (concerning performance and amount of code).

### Proposed solution

https://github.com/fantix/gino/blob/4a8c36e5654ca6960a5902171244ad3a312e89b3/gino/loader.py#L61

```
    def _do_load(self, row):
        rv = self.model()
        none_if_all_null = None
        for c in self.columns:
            if c in row:
                value = rv.__values__[c.name] = row[c]
                none_if_all_null = none_if_all_null or value

        return none_if_all_null and rv
```

**Comment by Badzyo** [comment]
This would be a good option, but I would like to note that such a change can break the already existing code in some projects that rely on current behavior. So it's better to put a deprecation notice for a while before changing.

**Comment by fantix** [comment]
Thanks for the input! Please see PR #282 if it fits.
