### ISSUE TITLE
Load model and custom columns in complex query result

### ISSUE THREAD

**Issue by jekel** [fantix/gino#308]
Hello!
Is there some loader combination which can load Model and additional columns for each row?
For example, i need to make sql query with join and aggregation functions... 
`db.select([User, db.func.count()]).select_from(User.join(...))`
and  possibility to iterate over results like this
`for user, users_count in await query...`
thanks

* GINO version: 0.7.5
* Python version: 3.6.5
* asyncpg version: 0.17.0
* aiocontextvars version: 0.1.2
* PostgreSQL version: 9.6.9

**Comment by jekel** [comment]
Cool, that works/
Can you update documentation please with such example? (i didn't find anything like this there..)

**Comment by fantix** [comment]
Yeah sounds like a good idea, will do!
