### ISSUE TITLE
Chained updates on models objects

### ISSUE THREAD

**Issue by jekel** [fantix/gino#337]
Hello!
I have an idea, to make possible to make something like that:

```python
class MyModel(db.Model):

  def set_status_a(self):
     return self.update(status='a')

  def set_state_b(self):
     return self.update(state='b')

... MyModel().set_status_a().set_state_b().apply()
```
But,  `update` methid returns `UpdateRequest` instance, so, for now it does not work, becase there is no method `set_state_b` 

I have tried dirty hack with monkeypatching `UpdateRequest.__getattr__` to call parent model method on next call, but this is bad approach

@wwwjfy @fantix what do you think about it? any ideas how to implement this?

**Comment by fantix** [comment]
You could override `UpdateRequest` to have your own methods, and use it in your own models:

```python
class MyModel:
    _update_request_cls = MyUpdateRequest
```
