### ISSUE TITLE
How to define multiple columns index?

### ISSUE THREAD

**Issue by jonahfang** [fantix/gino#37]

**Comment by fantix** [comment]
As described [here](http://docs.sqlalchemy.org/en/latest/core/constraints.html#indexes), you can define the index on multiple columns like this:

```
class User(db.Model):
    first_name = db.Column(db.Unicode())
    last_name = db.Column(db.Unicode())

db.Index('index_on_name', User.first_name, User.last_name)
```

Or, GINO also support the inline definition, by using `__table_args__` similar to the one from [SQLAlchemy ORM](http://docs.sqlalchemy.org/en/latest/orm/extensions/declarative/table_config.html#declarative-table-args):

```
class User(db.Model):
    first_name = db.Column(db.Unicode())
    last_name = db.Column(db.Unicode())

    __table_args__ = (
        db.Index('index_on_name', 'first_name', 'last_name'),
    )
```

(Using tuple, the ending comma is essential if there is only one item)

**Comment by jonahfang** [comment]
It works! Thanks.

**Comment by fantix** [comment]
Good to know 😃
