### ISSUE TITLE
Exists sql method

### ISSUE THREAD

**Issue by Illicitus** [fantix/gino#372]
Hi, can I use base sql methods like exists with GINO if it true, can you explain HOW?
For example I try use:
```python
db.func.exists(User.query.where(User.email == email)).gino.scalar()
```
 and it's didn't work.

**Comment by jekel** [comment]
You should use db.func.count to check record existance

**Comment by fantix** [comment]
`exists()` itself is [not executable](https://stackoverflow.com/a/44360816/3316267) - you'll need something like this:

```python
await db.scalar(db.exists(User.query.where(User.email == email)).select())
```

Please note, it should be `db.exists`, or the from clause will be wrong.

**Comment by Illicitus** [comment]
Hi guys, next your example works exactly like I need. Thanks [@fantic](https://github.com/fantix) for help and your answer.
```python
await db.scalar(db.exists(User.query.where(User.email == email)).select())
```
