### ISSUE TITLE
Select some fields with where 

### ISSUE THREAD

**Issue by yarara** [fantix/gino#375]
* GINO version: 0.7.1
* Python version: 3.6
* asyncpg version: 1.15.0
* aiocontextvars version:
* PostgreSQL version:

### Description

I need select some field with select() and where

### What I Did

```
denomination = await Denomination. \
        join(SettingsCurrency). \
        join(Currency). \
        select('value'). \
        where(and_(Currency.code == 'USD',
                   SettingsCurrency.settings_game_id.in_([s.id for s in settings_game]))).gino.all()
```
sql:
```
SELECT games_denomination.id, games_denomination.settings_currency_id, games_denomination.value, games_denomination."default", games_settingscurrency.id, games_settingscurrency.settings_game_id, games_settingscurrency.currency_id, games_currency.id, games_currency.name, games_currency.code, games_currency.is_active 
FROM games_denomination JOIN games_settingscurrency ON games_settingscurrency.id = games_denomination.settings_currency_id JOIN games_currency ON games_currency.id = games_settingscurrency.currency_id 
WHERE value AND games_currency.code = $1 AND games_settingscurrency.settings_game_id IN ($2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
```

error:
asyncpg.exceptions.DatatypeMismatchError: argument of AND must be type boolean, not type double precision

**Comment by wwwjfy** [comment]
You can see `value` is in where clause in the generated sql. The first parameter of `select` method in the `Join` clause is whereclause, refs 
https://docs.sqlalchemy.org/en/latest/core/selectable.html#sqlalchemy.sql.expression.Join.select

I think what you want is `db.select([Denomination.value]).select_from(Denomination.join(SettingsCurrency).join(Currency).where(...)`

**Comment by yarara** [comment]
I do it  without use 'db' (use models). 
I want like
```
Model.guery(field_name).join(Model2).where(....).gino.all()
```
but did not find how to do it

**Comment by wwwjfy** [comment]
Is there a reason you don't want to use `db`?
BTW, you can use `from sqlalchemy import select` if you don't want to have `db` object passed around.

If we have `Model.query(field_name)`, under the hood, it'll call `select`. The idea of Gino is to be a _lightweight_ ORM, so we use SQLAlchemy's core to build queries and use asyncio to execute. It won't be asyncio version SQLAlchemy, and light version of relationship/loader was "reinvented". Gino does have a few convenient methods for models like `get`, `update`, but won't have as many features as SQLAlchemy. It expects the users to have better control of the generated sql statements.

**Comment by yarara** [comment]
Thank you. I will try to use ```select```.

**Comment by wwwjfy** [comment]
Thanks for understanding. :)
