### ISSUE TITLE
Customise error class thrown from get_or_404

### ISSUE THREAD

**Issue by AmatanHead** [fantix/gino#38]
Hi!

As a tornado user I think `get_or_404` should throw a customizable error class.

I'm not sure where to put this setting though.

**Comment by wwwjfy** [comment]
Ideally, `get_or_404` could raise a corresponding exception from the web framework, so no `try..except` is necessary in the call sites. Like `NotFound` in `sanic`, `HTTPError` in `tornado`, `abort` in `flask`.

Unfortunately, `gino` only supports `sanic` now. Maybe we need some configuration, or something like extensions.

Any ideas are welcomed. Or even better, pull requests.

**Comment by AmatanHead** [comment]
> Maybe we need some configuration.

Configuration is clearly required. The only question is where to put it? I'm thinking about main `Gino` object, e.g.:

```python
db = Gino(settings={...})
```

**Comment by wwwjfy** [comment]
One thing I'd like to see is if it will fail, it should fail early. That's why I prefer the extension idea, because along with other initialization code, if the framework is wrongly appointed, the server won't even start.

But I haven't thought it through, maybe there is a better way to suit it in configuration and can avoid framework typo.

**Comment by AmatanHead** [comment]
I'd just provide a setting for 404 error class:

```python
settings = dict(not_found_error=NotFound)  # for sanic
settings = dict(not_found_error=lambda: HTTPError(404))  # for tornado
```

**Comment by AmatanHead** [comment]
Default could be the `gino.exceptions.NoSuchRowError`.

**Comment by wwwjfy** [comment]
For whoever to fix this issue to refer to: SQLAlchemy itself doesn't provide `get_or_404`. It's implemented by [Flask-SQLAlchemy](http://flask-sqlalchemy.pocoo.org).

This is another option.

**Comment by fantix** [comment]
Yeah I would vote for that - move `get_or_404` to `gino.ext.sanic`, make it that `db.Model` inherits from both `CRUDModel` and `SanicModelMixin` which has the `get_or_404` method (just need to modify a little bit of the newly created `declarative_base` method). In this case, Tornado could easily define a similar `get_or_404` in `gino.ext.tornado` for example.

**Comment by fantix** [comment]
Fixed with the `SanicModelMixin` solution. PR for `gino.ext.tornado` is greatly welcome!
