### ISSUE TITLE
one and one_or_none sqlalchemy methods support

### ISSUE THREAD

**Issue by fvolohin** [fantix/gino#385]
### Description

Sqlalchemy query api support methods `one` and `one_or_none.`
https://docs.sqlalchemy.org/en/latest/orm/query.html#sqlalchemy.orm.query.Query.one
https://docs.sqlalchemy.org/en/latest/orm/query.html#sqlalchemy.orm.query.Query.one_or_none
But gino didn't support them. This methods very convenient.

**Comment by wwwjfy** [comment]
Thanks for the advice.
