### ISSUE TITLE
Accessing unselected columns should raise an error rather that return None

### ISSUE THREAD

**Issue by AmatanHead** [fantix/gino#39]
Hello!

When one select columns with `Table.select()`, the returned object will have only part of attributes. Currently, gino (0.4.1) would return `None` when accessing attributes that weren't selected. However, accessing unselected attributes usually mean that there is a bug somewhere so it would be better to throw an appropriate error.

**Comment by fantix** [comment]
Or maybe by default it should return rows instead of objects? In latest master, user may choose returning rows or objects, by setting the boolean execution option `return_model`, which is `True` by default. For example:

```python
rows = await User.select('id', 'name').gino.all()
# This is returning User objects as for 0.4.1
# It's preferred to return rows(?)

rows = await User.select('id', 'name').execution_options(return_model=True).gino.all()
# Force returning User objects, with only id and name values, other columns are left None(?)
```

**Comment by fantix** [comment]
Fixed as example. Please reopen for further discussion if any.
