### ISSUE TITLE
对同一个表的多个外键join或者loader报错

### ISSUE THREAD

**Issue by YoshieraHuang** [fantix/gino#400]
* GINO version: 0.8.0
* Python version: 3.6.6
* asyncpg version:0.17.0
* aiocontextvars version: 0.2.0
* PostgreSQL version: 10.6 on Ubuntu

### Description
我有两个表，其中一个表中有两个外键都指向另一个表。我进行查询时，在postgreSQL中直接CROSS JOIN能够成功将两个外键都map成对应的数据。在gino中使用join，会出现 `sqlalchemy.exc.AmbiguousForeignKeysError`，并提醒我要显式定义`onclause`。我google了一下说`sqlalchemy`中可以通过定义`relationship`的`foreign_key`解决，但是gino中没有`relationship`。我又尝试使用`loader`来解决，load其中一个键是可行的，但是load两个键的话就会出现`asyncpg.exceptions.DuplicateAliasError`，关于这个错误网上的信息特别少。

所以，我该怎么使用gino去query呢，或者我该如何去定义join时的`onclause`呢？

### What I Did

```python
class Data_2sgg(db.Model):
    __tablename__ = "data_2sgg"

    vid = db.Column(db.Integer, primary_key=True)
    create_at = db.Column(db.DateTime)

    flyerName = db.Column(db.Unicode)
    flyer_vid = db.Column(db.Integer, db.ForeignKey('sample_2sgg.vid'))
    sampleName = db.Column(db.Unicode)
    sample_vid = db.Column(db.Integer, db.ForeignKey('sample_2sgg.vid'))

class Sample_2sgg(db.Model):
    __tablename__ = 'sample_2sgg'

    vid = db.Column(db.Integer, primary_key=True)
    create_at = db.Column(db.DateTime)
    material = db.Column(db.Unicode)
    shape = db.Column(db.Enum("circle", "square", "rectangle", "other", name="shape"))
    weight = db.Column(db.Float)
    thickness = db.Column(db.Float)

data = await Data_2sgg.join(Sample_2sgg).gino.first()
# sqlalchemy.exc.AmbiguousForeignKeysError: Can't determine join between 'data_2sgg' and 'sample_2sgg'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.

data = await Data_2sgg.load(
    flyer = Sample_2sgg.on(Sample_2sgg.vid == Data_2sgg.flyer_vid),
    sample = Sample_2sgg.on(Sample_2sgg.vid == Data_2sgg.sample_vid)
).gino.first()
# asyncpg.exceptions.DuplicateAliasError: table name "sample_2sgg" specified more than once
```

**Comment by fantix** [comment]
因为 SQLAlchemy 不会自动分派不同的别名（alias），所以这里需要手动分派：

```python
    Sample_2sgg_alias = Sample_2sgg.alias()
    data = await Data_2sgg.load(
        flyer=Sample_2sgg.on(Sample_2sgg.vid == Data_2sgg.flyer_vid),
        sample=Sample_2sgg_alias.on(Sample_2sgg_alias.vid == Data_2sgg.sample_vid)
    ).gino.first()
```

**Comment by YoshieraHuang** [comment]
It works, thank you!


| |
jwhuang
|
|
jwhuang@pims.ac.cn
|
签名由网易邮箱大师定制
在2018年12月1日 13:17，Fantix King<notifications@github.com> 写道：

因为 SQLAlchemy 不会自动分派不同的别名（alias），所以这里需要手动分派：

    Sample_2sgg_alias = Sample_2sgg.alias()

    data =await Data_2sgg.load(

        flyer=Sample_2sgg.on(Sample_2sgg.vid == Data_2sgg.flyer_vid),

        sample=Sample_2sgg_alias.on(Sample_2sgg_alias.vid == Data_2sgg.sample_vid)

    ).gino.first()
