### ISSUE TITLE
实体模型中包含JSONB字段并且含有JSONB中属性时，调用实体的to_dict()方法报错

### ISSUE THREAD

**Issue by beruhan** [fantix/gino#406]
```python
class VulnInfo(db.Model):

    __tablename__ = 'vuln_info'

    vul_json = Column('vul_json', JSONB, nullable=False)

    vul_mappings = db.ArrayProperty(prop_name='vul_json')
```

```
File "C:\Python36\lib\site-packages\sanic\app.py", line 603, in handle_request
    response = await response
  File "D:\work\project\vulsearch\vulsearch\api_1_0\vuln_info.py", line 33, in search_vuln
    print(vul_json.to_dict())
  File "C:\Python36\lib\site-packages\gino\crud.py", line 616, in to_dict
    return dict((k, getattr(self, k)) for k in keys)
  File "C:\Python36\lib\site-packages\gino\crud.py", line 616, in <genexpr>
    return dict((k, getattr(self, k)) for k in keys)
  File "C:\Python36\lib\site-packages\gino\json_support.py", line 38, in __get__
    val = self.get_profile(instance).get(self.name, NONE)
  File "C:\Python36\lib\site-packages\gino\json_support.py", line 60, in get_profile
    instance.__profile__[key] = props[key].decode(value)
KeyError: 'id'
```

**Comment by beruhan** [comment]
can anyone help me?

**Comment by wwwjfy** [comment]
如果有一段可以重现的代码，会有助于找到问题。目前看来怀疑可能是 column 的定义问题。

BR,
Tony

**Comment by beruhan** [comment]
from gino import Gino
from gino.dialects.asyncpg import JSONB
from sqlalchemy import Column
import asyncio

db = Gino()


class VulnInfoModel(db.Model):
    """实体"""
    __tablename__ = 'vuln_info_test'
    vul_json = Column('vul_json', JSONB, nullable=False)
    vul_mappings = db.ArrayProperty(prop_name='vul_json')


async def main():
    DB_ARGS = dict(
        host='10.10.13.112',
        port=5432,
        user='developer',
        password='Admin522522',
        database='device_info',
    )
    PG_URL = 'postgresql://{user}:{password}@{host}:{port}/{database}'.format(**DB_ARGS)
    await db.set_bind(PG_URL)
    await db.gino.create_all()

    vul_json = {
        "id": "IIE-IoT-0172763",
        "tags": [],
        "cvss_v2": {
            "severity": "MEDIUM",
            "base_score": 4.9,
            "vector_string": "AV:N/AC:H/Au:S/C:C/I:N/A:N"
        },
        "mappings": ["EDB-2011"]
    }

    # insert
    vuln = await VulnInfoModel.create(vul_json=vul_json)
    print(vuln.vul_json)
    # query
    vulns = await VulnInfoModel.query.gino.all()
    for vuln in vulns:
        print(vuln.to_dict())


asyncio.get_event_loop().run_until_complete(main())

**Comment by beruhan** [comment]
```# -*- coding: utf-8 -*-
from gino import Gino
from gino.dialects.asyncpg import JSONB
from sqlalchemy import Column
import asyncio

db = Gino()


class VulnInfoModel(db.Model):
    """实体"""
    __tablename__ = 'vuln_info_test'
    vul_json = Column('vul_json', JSONB, nullable=False)
    vul_mappings = db.ArrayProperty(prop_name='vul_json')


async def main():
    DB_ARGS = dict(
        host='10.10.13.112',
        port=5432,
        user='developer',
        password='Admin522522',
        database='device_info',
    )
    PG_URL = 'postgresql://{user}:{password}@{host}:{port}/{database}'.format(**DB_ARGS)
    await db.set_bind(PG_URL)
    await db.gino.create_all()

    vul_json = {
        "id": "IIE-IoT-0172763",
        "tags": [],
        "cvss_v2": {
            "severity": "MEDIUM",
            "base_score": 4.9,
            "vector_string": "AV:N/AC:H/Au:S/C:C/I:N/A:N"
        },
        "mappings": ["EDB-2011"]
    }

    # insert
    vuln = await VulnInfoModel.create(vul_json=vul_json)
    print(vuln.vul_json)
    # query
    vulns = await VulnInfoModel.query.gino.all()
    for vuln in vulns:
        print(vuln.to_dict())


asyncio.get_event_loop().run_until_complete(main())
```

例子如上，如果注销掉VulnInfoModel中的vul_mappings,则不会出现上述错误

**Comment by wwwjfy** [comment]
感谢提供例子。
这里的原因是 `vul_json` 中包含了 `id`, `tags` 等 key，但是在 `VulnInfoModel` 中没有定义，因此在做映射的时候就出错了。
出错的信息确实不太友好，需要改进。

这样的做法不太推荐。因为如果不是 Gino 来管理所有 json 字段中的内容，在更新的时候就会将原有内容覆盖，造成数据丢失。

定义成如下这样就没有问题了。另外，建议在 `VulnInfoModel.create` 中使用各 json 属性而不是直接对 `vul_json` 进行操作。原因同上。

```python
class VulnInfoModel(db.Model):
    """实体"""
    __tablename__ = 'vuln_info_test'
    vul_json = Column('vul_json', JSONB, nullable=False)
    id = db.StringProperty(prop_name='vul_json')
    tags = db.ArrayProperty(prop_name='vul_json')
    cvss_v2 = db.ObjectProperty(prop_name='vul_json')
    mappings = db.ArrayProperty(prop_name='vul_json')
```

**Comment by beruhan** [comment]
感谢解答，还有一个问题，如果vul_json 结构非常复杂，vul_json 属性的值还是json，是不是要在模型中列出所有属性，还是只列出vul_json 的属性呢，有没有一个优雅的解决办法呢

**Comment by wwwjfy** [comment]
取决于如何使用/管理 `vul_json` 中的值。如果使用 Gino 来管理，需要定义所有属性，如果手动管理，就作为普通的 dict 使用就好。只是所有属性需要统一的方式，不能一半属性是手动管理，一半是 Gino 管理，也就会出现之前出现的问题。
