### ISSUE TITLE
How to write sum/count query by gino?

### ISSUE THREAD

**Issue by jonahfang** [fantix/gino#41]

**Comment by fantix** [comment]
Use `db.func.sum` or `db.func.count`. See [this](http://docs.sqlalchemy.org/en/latest/core/tutorial.html#functions) and [this](http://docs.sqlalchemy.org/en/latest/core/sqlelement.html#sqlalchemy.sql.expression.func).

**Comment by jonahfang** [comment]
```
User.select(db.func.sum(User.id))
```
Not works!

**Comment by fantix** [comment]
No it should be:

```python
await db.scalar(db.select([db.func.sum(User.id)]))
```

**Comment by jonahfang** [comment]
返回值不对.

**Comment by fantix** [comment]
https://www.postgresql.org/docs/current/static/functions-aggregate.html

看 `sum` 的返回值类型，以及

https://magicstack.github.io/asyncpg/current/usage.html#type-conversion

asyncpg 会把他们转换成什么类型。

**Comment by jonahfang** [comment]
Sorry, It works! Thanks.
