### ISSUE TITLE
How I can write query, which return all descendants of a node of graph in Gino?

### ISSUE THREAD

**Issue by toddbarry** [fantix/gino#425]
* GINO version: 0.7.5
* Python version: 3.7.0
* asyncpg version: 0.17.0
* aiocontextvars version: none
* PostgreSQL version: 10.4

### Description

Hello, i want to get all descendants of a given node. My problem is identical to problem, which described in [this](https://stackoverflow.com/questions/52408644/how-can-i-write-a-sqlalchemy-query-that-will-return-all-descendants-of-a-node-in) question. The solve is turn out very simple for SQLAlchemy, but, I can't apply this solve for Gino because, as I can understand, similar queries realized in Gino with using the loaders.
The simple solution of getting the direct childs of current parent element is shown in official [documentation](http://gino.fantix.pro/en/latest/loaders.html) but i can not understand, how apply this information for solve my problem.

In fact I see the ideal way for searching all descendants of current parent element - is using a complementary table called Edges, which store the information about relationships of nodes in graph - each row in Edges table have two parameters - ids of target and source nodes of edge in graph.

````
class Nodes(db.Model):
    __tablename__ = "nodes"

    id = db.Column(db.Integer, primary_key=True)
    info = db.Column(db.Text)

class Edges(db.Model):
    __tablename__ = "edges"

    id = db.Column(db.Integer, primary_key=True)
    source = db.Column(db.Integer, db.ForeignKey('nodes.id'))
    target = db.Column(db.Integer, db.ForeignKey('nodes.id'))

    _edge_idx = db.Index("edge_idx", "source", "target", unique=True)
````

and query find all edges whose parameter 'source' matches the specified id value of current node and take the 'target' values of each on first iteration. Then it repeats all actions for this 'target' values - i.e. it finds all edges whose parameter 'source' coincides with one of the previously found 'target' values. e.t.c

Please, help solve this task, I think I can not do it myself.

Thank you

**Comment by wwwjfy** [comment]
As Gino uses SQLAlchemy core to build queries, there almost always are an equivalent version in Gino of a working snippet in SQLAlchemy. The biggest difference would be instead of SQLAlchemy's query, `sqlalchemy.sql.expressions` variants are being used.
For example, `session.query(User.id)` in SQLAlchemy equals to `select([User.id])` in SQLAlchemy, and it equals to `select([User.id])` in Gino. (contexts are omitted, but the generated sql statements are the same).

In this case, if you want to use CTE mentioned in the stackoverflow answer, the examples in SQLAlchemy [cte function document](https://docs.sqlalchemy.org/en/latest/core/selectable.html#sqlalchemy.sql.expression.CompoundSelect.cte) should work in Gino with minimum changes.

**Comment by toddbarry** [comment]
But when I try to import a relationship method I get an exception:
`AttributeError: 'Gino' object has no attribute 'relationship'`

```
class Nodes(db.Model):
    __tablename__ = 'nodes'

    id = db.Column(db.Integer, primary_key=True)
    child = relationship('nodes', secondary='edges', backref='parent')

    def __init__(self, *args, **kwargs):
        super(Nodes, self).__init__(*args, **kwargs)

class Edges(db.Model):
    __tablename__ = 'edges'

    id = db.Column(db.Integer, primary_key=True)
    source = db.Column(db.Integer, db.ForeignKey('nodes.id'))
    target = db.Column(db.Integer, db.ForeignKey('nodes.id'))

    _edge_idx = db.Index('edge_idx', 'source', 'target', unique=True)

    def __init__(self, *args, **kwargs):
        super(Edges, self).__init__(*args, **kwargs)
```
and in the documentation I did not find any mention of the relationship method. There, instead of using relationship, it is proposed to use loaders to create many-to-many relationships and search for all the heirs of the object.

**Comment by wwwjfy** [comment]
Sorry I missed that. `relationship` is not supported, we use loaders instead as you see.
Let me try to get a demo.

**Comment by wwwjfy** [comment]
Correction: loaders are not a replacement for relationship in queries, but only when loading results, as the name suggests. Apologies for the misleading.

This is almost a direct translation of the example in the stackoverflow answer, leaving out the table creation and objects insertion parts.

https://gist.github.com/wwwjfy/c46cd635ebe97183c73c45c19c9cab74

**Comment by toddbarry** [comment]
Thank you, wwwjfy! I want to try to implement this algorithm without using property_1 and property_2, because I don't need to get a path to a descendants, but u helped me understand how to get around the problem with queries to a models with multiple foreign keys. I need some time to change the algorithm and remove the property_1 and property_2 from it.

**Comment by wwwjfy** [comment]
Glad to help 😃
I'm closing the issue. Feel free to reopen if you have further questions.

**Comment by wwwjfy** [comment]
Sorry I missed this last message. I think it's fine to not use loaders, as long as you can get what you want. Loaders are just for convenience purpose.
