### ISSUE TITLE
Retry options in init_app for Sanic

### ISSUE THREAD

**Issue by choco** [fantix/gino#426]
* GINO version: 0.8.1
* Python version: 3.7
* asyncpg version: 0.18.2
* aiocontextvars version:
* PostgreSQL version: 11

### Description

Today I was trying to write a simple app using docker-compose. One service is the database service and another is the web-app written with Sanic and GINO.
When starting both of these, since Postgres takes it's time starting up, I'll get an error from Sanic `ConnectionRefused` etc...
Is there any way or is there any plan to add options for retrying the connection?

### What I Did

Started a Sanic app with Gino using Gino.ext.sanic configured as follow
```
app = Sanic()
app.config.DB_HOST = 'db-service'
app.config.DB_DATABASE = 'vpn_service'
app.config.DB_USER = 'postgres'
app.config.DB_PASSWORD = 'postgres'
db.init_app(app)
```
Get a traceback with a `ConnectionRefused` starting from the `set_bind` inside the `Gino.ext.sanic` module.

**Comment by choco** [comment]
That makes absolute sense.
This doesn't work with the Sanic extension because `set_bind` is called in a tagged function `before_server_start` which is only registered by `init_app`
So right now I have to monkey patch the `set_bind` function in `gino.ext.sanic`  to obtain a similar result.

**Comment by wwwjfy** [comment]
You're right. It's not elegant for Sanic extension.
The other way is to test the connectivity before setting up the Sanic server and init_app. Using `nc` in start script or something in Python like

```python
import socket

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(("localhost", 5432))
```

Sorry I can't think of a better solution now.
