### ISSUE TITLE
How to write scalar subquery by Gino?

### ISSUE THREAD

**Issue by jonahfang** [fantix/gino#43]
In SQLAlchemy, it may like this:
```
SELECT
    users.name,
    (SELECT count(addresses.id) AS count_1 FROM addresses WHERE users.id = addresses.user_id) AS anon_1
FROM users

stmt = select([func.count(addresses.c.id)]).where(users.c.id == addresses.c.user_id).as_scalar()
conn.execute(select([users.c.name, stmt])).fetchall()
```

**Comment by fantix** [comment]
```python
stmt = select([func.count(addresses.c.id)]).where(users.c.id == addresses.c.user_id).as_scalar()
await db.all(select([users.c.name, stmt]))
```

**Comment by wwwjfy** [comment]
I think it's not really an "issue". Should we have some kind of forum for questions (not issues or PRs) like stackoverflow or google group?
We can pick some FAQ to put in documentations later.

**Comment by jonahfang** [comment]
Thanks, it works:
```
    stmt = db.select([db.func.count(UserDetail.id)]).where(User.id==UserDetail.user_id).label("f1")
    rs = await db.all(db.select([User.nickname, stmt]))
    for r in rs:
        print(r['nickname'],r['f1'])  #asyncpg.Record
```
But how to automatically include all User columns in SELECT clause? Something like:
```
rs = await db.all(db.select([User.*, stmt]))
```

**Comment by fantix** [comment]
@wwwjfy  Yeah, stackoverflow sounds like an ideal solution. `python-gino` would be the good tag to do so.

**Comment by fantix** [comment]
@jonahfang it would be `[*User.__table__.columns, stmt]`

**Comment by jonahfang** [comment]
Thanks!

**Comment by AmatanHead** [comment]
> Yeah, stackoverflow sounds like an ideal solution

There's also gitter.

> [*User.__table__.columns, stmt]

Wouldn't adding support for something like `[User, stmt]` be a good idea?

**Comment by fantix** [comment]
@AmatanHead thx for commenting.

The closest implementation would be adding a `__iter__` to the meta class of `Model`, returning an iterator for all columns, and use it like this: `db.select([*User, stmt])`. Not bad, any objection?

**Comment by jonahfang** [comment]
Good!
