### ISSUE TITLE
count the number of rows with where condition with gino

### ISSUE THREAD

**Issue by mtajay** [fantix/gino#443]
* GINO version: 0.8.1
* Python version: 3.7
* asyncpg version: 
* aiocontextvars version:
* PostgreSQL version: 

### Description

I am trying to fetch count of the number of rows present based on a couple of conditions on the same table. I am unable to find any relevant help/example regarding this.

This is what I tried.
```
upcoming_count = await (db.func.count(Meeting.query
                                                .where(and_(Meeting.status == MeetingStatus.SCHEDULED,
                                                                      Meeting.start_at < some_time_from_now(window))))
                                                .gino
                                                .scalar())
```

**Comment by wwwjfy** [comment]
This might be what you want:
```
upcoming_count = await (db.select([db.func.count()])
                                                .where(and_(Meeting.status == MeetingStatus.SCHEDULED,
                                                                      Meeting.start_at < some_time_from_now(window))))
                                                .gino
                                                .scalar())
```

**Comment by mtajay** [comment]
Thanks, @wwwjfy for replying so quickly, It worked. Was this already documented somewhere?

**Comment by wwwjfy** [comment]
This is actually SQLAlchemy syntax. You can check their documentations or search by that.
The previous query doesn't work because db.func.count is not a query but, as the name suggests, a function, which means `count(...)`, but database would need `select count(...) from table`.

**Comment by rysev-a** [comment]
Hello, how i can get prepared query count?

I update my query many times, `my_query = my_query.where(some_operations_with_filters_in_other_methods)`

I see my_query.count method, in SQLAlchemy i just can get my_query.count(), can i get something like this in Gino?

**Comment by wwwjfy** [comment]
@rysev-a you should be able to use same as SQLAlchemy unless it's ORM related, because Gino is using the SQLAlchemy's query engine.

Would you mind giving an example then I can try to get a workable one?
