### ISSUE TITLE
enable_task_local doesn't work with tornado

### ISSUE THREAD

**Issue by AmatanHead** [fantix/gino#45]
So, I've started writing tornado extension and realized that `enable_task_local` doesn't work inside of the tornado handlers. The reason is that tornado doesn't wrap its request into tasks so `asyncio.Task.current_task()` always returns `None`.

**Comment by AmatanHead** [comment]
So far I see no way of implementing task locals when using tornado.

The tornado itself doesn't create tasks for every request. It seems like tornado doesn't have the concept of tasks at all...

**Comment by fantix** [comment]
Thanks a lot for the help on Tornado! Yeah it is a bit different as you tried. We may also spare some time on it too, but for now the focus is on stabilizing the core APIs, writing tests and push it production ready. In the meantime, we appreciate any pull requests about any part. 😺
