### ISSUE TITLE
Setting timeout for all connections

### ISSUE THREAD

**Issue by Tiagoantunes52** [fantix/gino#453]
* GINO version: 0.8.1
* Python version: 3.6.6
* asyncpg version: 0.18.2
* aiocontextvars version: 0.2.1
* PostgreSQL version: 10.6

### Description

Hi,
I am using gino and sanic extension and I am trying to figure out how to set a timeout for all connections.

### What I Did
I modified the set_bind method in api.py and it seemed to work. Just updated the execution options with the timeout.
 
```python
    async def set_bind(self, bind, loop=None, **kwargs):
        """
        Bind self to the given :class:`~.engine.GinoEngine` and return it.

        If the given ``bind`` is a string or
        :class:`~sqlalchemy.engine.url.URL`, all arguments will be sent to
        :func:`~gino.create_engine` to create a new engine, and return it.

        :return: :class:`~.engine.GinoEngine`

        """
        if isinstance(bind, str):
            bind = make_url(bind)
        if isinstance(bind, URL):
            from . import create_engine
            bind = await create_engine(bind, loop=loop, **kwargs)
            bind.update_execution_options(timeout=1)
        self.bind = bind
        return bind
```

Yet the best way would be to set this timeout as a config variable and then pass it as a kwarg to the set_bind method in api.py.

What do you think?

Thanks

**Comment by fantix** [comment]
Would the [`command_timeout` from asyncpg](https://magicstack.github.io/asyncpg/current/api/index.html#asyncpg.connection.connect) do?

**Comment by Tiagoantunes52** [comment]
The  ```command_timeout``` worked just fine, I was able to set a config variable with the timeout value I wanted, but in order to use it there is the need for a slight modification in sanic extension (sanic.py) when passing the arguments to ```set_bind```

```python
        async def before_server_start(_, loop):
            if app.config.get('DB_DSN'):
                dsn = app.config.DB_DSN
            else:
                dsn = URL(
                    drivername=app.config.setdefault('DB_DRIVER', 'asyncpg'),
                    host=app.config.setdefault('DB_HOST', 'localhost'),
                    port=app.config.setdefault('DB_PORT', 5432),
                    username=app.config.setdefault('DB_USER', 'postgres'),
                    password=app.config.setdefault('DB_PASSWORD', ''),
                    database=app.config.setdefault('DB_DATABASE', 'postgres'),
                )

            await self.set_bind(
                dsn,
                echo=app.config.setdefault('DB_ECHO', False),
                min_size=app.config.setdefault('DB_POOL_MIN_SIZE', 5),
                max_size=app.config.setdefault('DB_POOL_MAX_SIZE', 10),
                ssl=app.config.setdefault('DB_SSL'),
                loop=loop,
                command_timeout=app.config.setdefault('DB_COMMAND_TIMEOUT', 60.0)
            )
```

Do you agree?

Thanks

**Comment by wwwjfy** [comment]
`command_timeout` can be passed in `DB_KWARGS`, which will pass, in turn, everything to asyncpg.

**Comment by Tiagoantunes52** [comment]
Thanks, ```DB_KWARGS``` worked! 

Unfortunately I was using gino version 0.8.1, and didn't notice the changes made for release 0.8.2, which solved the problem.

Also the documentation in:
[https://python-gino.readthedocs.io/en/latest/sanic.html](https://python-gino.readthedocs.io/en/latest/sanic.html)
and 
[https://python-gino.readthedocs.io/zh/latest/sanic.html](https://python-gino.readthedocs.io/zh/latest/sanic.html)
regarding DB_KWARGS is conflicting

**Comment by wwwjfy** [comment]
Looks like the former document is not updated, as it shows 0.8.1
If it's still like this tomorrow, I'll check readthedocs

**Comment by fantix** [comment]
@wwwjfy yeah for some reason it's not triggered for 2 months, I rebuild the latest and setup GitHub hook, let's see if that works.
