### ISSUE TITLE
attribute 'db' in aiohttp.py

### ISSUE THREAD

**Issue by EvgenyUsov** [fantix/gino#457]
### Description
Hi! I am using gino and aiohttp extension and in my application there is already a db attribute. Can send attribute name in arguments?

### For example:

```
def init_app(self, app, config = None, attr = 'db'):
    app[attr] = self
```

https://github.com/fantix/gino/blob/d50fb882fbf3adf38b04f70da0f7d71574768081/gino/ext/aiohttp.py#L118

What do you think?

Thank

**Comment by fantix** [comment]
Oh yes, for sure!

**Comment by EvgenyUsov** [comment]
This is cool. Thank!
