### ISSUE TITLE
Query intersection and checking for IS NULL

### ISSUE THREAD

**Issue by paulin-mipt** [fantix/gino#468]
* GINO version: 0.8.2
* Python version: 3.6.7
* asyncpg version: 0.18.3
* aiocontextvars version: 0.2.1
* PostgreSQL version: 10.7

### Description

I was trying to express in Gino syntax query like `SELECT * FROM dbname WHERE key1=value AND key2 IS NULL`

### What I Did
Intuitively I wrote this:
```
result = await MyModel.query.where(
        MyModel.key1 == value and
        MyModel.key2 is None
    ).gino.all()
```
I figured out I did both things wrong -- query intersection and IS NULL checking. 

1. Is it true that multiple WHERE conditions has to be chained, like query.where(...).where(...)? Are there two actual queries (speaking about performance)?
2. Maybe you could consider supporting also `is None` / `is not None`? There's nothing wrong with `== None` but it's just more pythonic way to go :)

P.S. Thank you, you're doing a really great job!

**Comment by fantix** [comment]
SQLAlchemy core documentation might really help here, please see links below inline:

> 1. Is it true that multiple WHERE conditions has to be chained, like query.where(...).where(...)? Are there two actual queries (speaking about performance)?

You may chain `where()` calls, or use [`db.and_()`](https://docs.sqlalchemy.org/en/latest/core/sqlelement.html#sqlalchemy.sql.expression.and_).

> 2. Maybe you could consider supporting also is None / is not None? There's nothing wrong with == None but it's just more pythonic way to go :)

You should use [`MyModel.key2.is_(None)`](https://docs.sqlalchemy.org/en/latest/core/sqlelement.html#sqlalchemy.sql.operators.ColumnOperators.is_) or [`MyModel.key2.isnot(None)`](https://docs.sqlalchemy.org/en/latest/core/sqlelement.html#sqlalchemy.sql.operators.ColumnOperators.isnot).

Thanks for using GINO! ❤️

**Comment by paulin-mipt** [comment]
Thanks for quick answer! I have one more brief question but it's better to create another one, so closing this

**Comment by MuzaffarAliShah** [comment]
How to use OR with where

**Comment by fantix** [comment]
@MuzaffarAliShah https://docs.sqlalchemy.org/en/13/core/tutorial.html#conjunctions
