### ISSUE TITLE
Specify schema for a table

### ISSUE THREAD

**Issue by paulin-mipt** [fantix/gino#473]
* GINO version: 0.8.2
* Python version: 3.6.7
* asyncpg version: 0.18.3
* aiocontextvars version: 0.2.1
* PostgreSQL version: 10.7

### Description
I want to specify a schema for my table (I mean the one you create with `CREATE SCHEMA schema_name;`). 

It doesn't work out when I'm doing just `__tablename__ = schema_name.mytable` saying the relation does not exist, so I wonder if it's possible to do it in any other way. Tried to read the sources but no success yet.

**Comment by fantix** [comment]
You could either specify schema globally:

```python
import asyncio

import gino
from sqlalchemy.schema import CreateSchema

db = gino.Gino(schema='schema_name')


class MyTable(db.Model):
    __tablename__ = 'mytable'


async def main():
    async with db.with_bind('postgresql://localhost/gino', echo=True):
        await db.status(CreateSchema('schema_name'))
        await db.gino.create_all()


asyncio.run(main())
```

or do it per table:

```python
db = gino.Gino()


class MyTable(db.Model):
    __tablename__ = 'mytable'
    __table_args__ = dict(schema='schema_name')
```

**Comment by paulin-mipt** [comment]
The global way was exactly what I wanted, thanks.

Looking forward to see improved documentation with tons of examples, pretty sure you're already working on it!

**Comment by fantix** [comment]
@paulin-mipt yeah thanks for understanding! we'll try to make time to enhance the docs ;)

**Comment by SandaruThilakarathne** [comment]
Is there any method to change the schema based on the request header? assume that in the request header there is a key called schema and based on that we need to take data from the table. So can we change the Schema by adding a middle ware to check each request?
