### ISSUE TITLE
Clarification of Get Connected example

### ISSUE THREAD

**Issue by ajmcateer** [fantix/gino#486]
* GINO version: 0.82
* Python version: 3.7.2
* sqlite

### Description
I was looking at the examples and saw the following setup.
```
import asyncio

async def main():
    await db.set_bind('postgresql://localhost/gino')

asyncio.get_event_loop().run_until_complete(main())
```
I am trying to use gino with starlette, I am converting over from flask and I am trying to translate this setup below from flask-sqlalchemy to gino

```
class Channel(db.Model):

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(120), unique=True, nullable=False)
```

```
@bp.route('/create', methods=['POST'])
def register():
    name = request.form.get('name')
    icon = request.form.get('icon')

    channel = Channel(name=name, icon=icon)
    db.session.add(channel)
    db.session.commit()
    return jsonify(channel.dict(True))
```

How would I handle that if everything has to go in the main method.

**Comment by wwwjfy** [comment]
Could you clarify what are you trying to achieve?
If I understand correctly, you can refer to extensions, e.g. http://gino.fantix.pro/en/latest/sanic.html

**Comment by ajmcateer** [comment]
The example you posted with sanic is what I am looking for but with Starlette it handles configuration differently and doesn't have app.config. I want to use Starlette as it has better websocket support.

**Comment by wwwjfy** [comment]
Right. Then we need add Starlette extension.

**Comment by ajmcateer** [comment]
If you can point me in the right direction I can give it a shot.

**Comment by leosussan** [comment]
@ajmcateer I'm using FastAPI with GINO, which is based on Starlette. Made some modifications - this seemed to work for me.

This example makes use of Starlette's event handlers.

> from app.models import db
> from starlette.applications import Starlette
> from starlette.responses import JSONResponse
> 
> app = Starlette()
> DATABASE_URI = 'postgresql://'
> 
> @app.route('/')
> async def main(request):
>     channel = await Channel.create(name=name, icon=icon)
>     return JSONResponse(channel.__values__)
> 
> 
> @app.on_event("startup")
> async def startup():
>     await db.set_bind(DATABASE_URI)
> 
> 
> @app.on_event("shutdown")
> async def shutdown():
>     await db.pop_bind().close()
>

**Comment by leosussan** [comment]
That said - I'd love native support for Starlette & FastAPI.

**Comment by wwwjfy** [comment]
Thanks @leosussan. The extension would do similar as in your snippet.
@ajmcateer you can check code in other extensions.

**Comment by leosussan** [comment]
> Thanks @leosussan. The extension would do similar as in your snippet.
> @ajmcateer you can check code in other extensions.

Yeah - still, there are things that could be made simpler, specifically on the config side (a la what you've got for Sanic). 

Big fan of GINO, btw - love what you're doing with it. Might make a cookiecutter repo w/ Starlette / FastAPI for you to point to for future questions like this.

**Comment by wwwjfy** [comment]
I've submitted a PR #497. Feel free to report issue. :)
