### ISSUE TITLE
Gino engine is not initialized.

### ISSUE THREAD

**Issue by hdgone** [fantix/gino#501]
* GINO version: 0.8.3
* Python version: 3.7
* asyncpg version: 0.18.3
* aiocontextvars version: 0.2.2
* PostgreSQL version: 9.4

### Description

I'm trying to create a simple API using aiohttp and Gino. The point is to make abstract generic views where I can only pass the model and it'll create views for it.

### What I Did

I created models and ran migrations using db.gino.create_all() . It worked fine but when I pass the model to my Endpoint class where I need to make a query, it fails with:

> gino.exceptions.UninitializedError: Gino engine is not initialized.

My Endpoint class:

```python

class ListEndpoint(Endpoint):
    def __init__(self, model):
        super().__init__()
        self.model = model

    async def get(self) -> Response:
        obj_list = await self.model.query.gino.all()

        if not obj_list:
            return Response(
                status=404,
                body=json.dumps({'Not found': 404}),
                content_type='application/json'
            )

        data = await ModelSerializer(obj_list).to_json()

        return Response(
            status=200, body=data, content_type='application/json'
        )
```

looks like it fails on:

```python
obj_list = await self.model.query.gino.all()
```

I thought it was enough for engine config. DB_ADDRESS looks like this:

> postgresql://admin:pass@localhost:5432/library

But I also added config with 'dsn' on init_app.
My code from main.py:

```python
from aiohttp.web import Application, run_app

from models import Country
from resource import GenericResource
from settings import DB_ADDRESS

from gino.ext.aiohttp import Gino


app = Application()
db = Gino()

db.init_app(
    app,
    config={
        'dsn': DB_ADDRESS
    }
)
countries = GenericResource('countries', Country)
countries.register(app.router)


if __name__ == '__main__':
    run_app(app)
```

What's wrong? And I've also got a question, is this fine using async with db.with_bind every time I need to hit database? Thanks in advance!

**Comment by mikekeda** [comment]
My guess, you don't have db object in your Country model so model isn't binded.
Does db.gino.create_all() create Country table?
Could you show the code for Country model?

**Comment by fantix** [comment]
> is this fine using `async with db.with_bind` every time I need to hit database? 

This is not good - on exiting the `with` block, the engine will be closed. That means you are probably creating new database connections every time hitting the database, instead of reusing the pooled connections.

**Comment by fantix** [comment]
> Could you show the code for Country model?

Right, I cannot reproduce your issue either. It would be helpful if you could show more code, like what `countries.register()` does, etc.

**Comment by hdgone** [comment]
My country model:
```
class Country(db.Model):
    __tablename__ =  'countries'

    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(150))
```

I've actually managed to fix this error by doing the following:
```
async def main(loop):

    await db.set_bind(DB_ADDRESS)
    db = Gino()
    app = Application(middlewares=[db])

    db.init_app(
        app,
        config={
            'dsn': DB_ADDRESS
        }
    )

    resource = GenericResource('countries', Country)
    resource.register(app.router)

    return app
```

And then:
```
if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    app = loop.run_until_complete(main(loop))
    run_app(app)

```

My GenericResource class:
```
class GenericResource:
    """
    Handles routing based upon given model
    :param resource_name: resource name used in routing
    :param model: model to organise resource around
    """

    def __init__(self, resource_name, model):
        self.resource_name = resource_name

        self.instance_endpoint = InstanceEndpoint(model)
        self.list_endpoint = ListEndpoint(model)

    def register(self, router: UrlDispatcher):
        router.add_route(
            '*', f'/{self.resource_name}/{{instance_id}}',
            self.instance_endpoint.dispatch
        )
        router.add_route(
            '*', f"/{self.resource_name}",
            self.list_endpoint.dispatch
        )

```

But as @fantix mentioned, db has to be initialized only once in application, but this code seems to do it twice.

**Comment by fantix** [comment]
Are you talking about these first two lines in `main()`?

```python
    await db.set_bind(DB_ADDRESS)
    db = Gino()
```

This doesn't make sense to me because you are referencing `db` (line 1) before defining it (line 2).

**Comment by hdgone** [comment]
I figured out what the problem was. I was using different instances of Gino() inside models.py and main.py. As the solution, I've created a single Gino() instance only once and imported it inside other files.
