### ISSUE TITLE
Manual transaction control broken

### ISSUE THREAD

**Issue by EasyLovv** [fantix/gino#511]
* GINO version: 0.8.3
* Python version: 3.7.2
* asyncpg version: 0.18.3
* aiocontextvars version: 0.2.2
* PostgreSQL version: 11.4

### Description

The [Manual transaction control](http://gino.fantix.pro/en/latest/transaction.html#manual-control) usage is broken, I'm trying to use transactions with manual control, but I'm getting an exception below, I found a workaround, with awaiting `__aenter__`, which is not described in the documentation, can you please fix the code if you are going to support the approach described in documentation or change the documentation, if you don't.

### Exception

```
tx = await db.transaction()
E       TypeError: object _TransactionContext can't be used in 'await' expression
```

**Comment by wwwjfy** [comment]
Thanks for reporting! The doc is fixed.
