### ISSUE TITLE
Compatibility with Sanic 19.6.2

### ISSUE THREAD

**Issue by tng10** [fantix/gino#519]
* GINO version: 0.8.3
* Python version: 3.6.8
* asyncpg version: 0.18.2
* aiocontextvars version: 0.2.1
* PostgreSQL version: 11.3

### Description

Regarding the newest version of Sanic (19.6.2), an ASGI interface was introduced and since ASGI lifespan protocol has support for only two server events, we no longer can make usage of ```before_server_start``` and ```after_server_stop``` server events.

As a suggestion the file `ext/sanic.py` will need to have its server events replaced in order to be compatible with ASGI interface.

Decorator of the method `before_server_start`

**from**
```
@app.listener('before_server_start')
```

**to**
```
@app.listener('after_server_start')
```

Decorator of the method `after_server_stop`

**from**
```
@app.listener('after_server_stop')
```

**to**
```
@app.listener('before_server_stop')
```

What do you guys think about it?

**Comment by tng10** [comment]
In case you want to take a look on it, I just opened a PR #520 for it.

**Comment by wwwjfy** [comment]
close as #520 is merged
