### ISSUE TITLE
Retrieve query with filter based on a dictionary

### ISSUE THREAD

**Issue by snguyenthanh** [fantix/gino#522]
* GINO version: 0.8.3
* Python version: 3.7.3
* asyncpg version: 0.18.3
* aiocontextvars version: 0.2.2
* PostgreSQL version: 11.4

### Description

I'm using Sanic with Gino. The `request.args` returned from Sanic is in `dictionary` format, and I would love to pass it to a Gino model to retrieve the rows that satisfies the key-values in `request.args`.

For example:
```
request.args = {
    'gender': 'male',
    'job': 'teacher',
}

users = User.query.where(**request.args).gino.all()
```

In Gino, are there any ways to achieve the above thing ?

Or using something similiar to [Query.filter_by](https://docs.sqlalchemy.org/en/13/orm/query.html) in `SQLAlchemy`.

**Comment by mikekeda** [comment]
try this:
```
from sqlalchemy import and_

users = User.query.where(and_(*[
        getattr(User, k) == v
        for k, v in request.args.items()
        if hasattr(User, k)
    ]).gino.all()
```

**Comment by snguyenthanh** [comment]
> try this:
> 
> ```
> from sqlalchemy import and_
> 
> users = await User.query.where(and_(*[getattr(User, k) == v for k, v in request.args.items()])).gino.all()
> ```

Thanks @mikekeda. I used the code block you advise, and have the following error
```
File "/Users/.../gds_backend/views/user.py", line 38, in user_get
    return json({"data": data})
  File "/Users/.../.local/share/virtualenvs/venv/lib/python3.7/site-packages/sanic/response.py", line 234, in json
    dumps(body, **kwargs),
OverflowError: Maximum recursion level reached
```

Could anyone please help look if I do anything wrong:
```
@blueprint.route("/", methods=["GET", "POST"])
async def user_route(request):
    # Sanic request.args stores values in <list>
    args = {key: val[-1] for key, val in args.items()}

    users = await User.query.where(
            and_(*[getattr(User, k) == v for k, v in args.items()])
        ).gino.all()
    return json({"data": users})
```

**Comment by snguyenthanh** [comment]
I have a very weird related issue:


> try this:
> 
> ```
> from sqlalchemy import and_
> 
> users = await User.query.where(and_(*[getattr(User, k) == v for k, v in request.args.items()])).gino.all()
> ```

`users` returns `None` in this case. It also returns `None` when I replace the `==` with `operator.eq`.

**Comment by mikekeda** [comment]
check generated sql and try to run it on your db

```
from sqlalchemy.dialects import postgresql  # if you use postgresql

query = User.query.where(and_(*[getattr(User, k) == v for k, v in request.args.items()]))
print(query.compile(dialect=postgresql.dialect(), compile_kwargs={"literal_binds": True}))
```

**Comment by snguyenthanh** [comment]
The reason why it didn't work earlier, maybe because of the code structure on my side:

```
# views.py
query = get_query(args, User)
users = await query.gino.all()

# utils.py
def get_query(args, model):
    return model.query.where(
        and_(*(
            getattr(model, k) == v
            for k, v in args.items()
        ))
    )
```

I dont know why this doesn't work. But when I move the execution of the query to `get_query`, it works as expected.

**Comment by wwwjfy** [comment]
It's not safe to use user input directly. And the validation and conversion can happen at the same time. For example

```python
valid_args = {'gender': User.gender}

db_args = [valid_args[key] for key in query_args if key in valid_args]
```

**Comment by snguyenthanh** [comment]
Thanks @wwwjfy for the tips.

I use Cerberus for input validation and conversion before processing. Do you think it is safe enough ?

**Comment by wwwjfy** [comment]
I haven't used Cerberus, but as long as no unexpected parameters sent to the query, it should be fine. :)
