### ISSUE TITLE
Transaction rollback .. rough

### ISSUE THREAD

**Issue by mikepc** [fantix/gino#536]
* GINO version: 0.8.3
* Python version: 3.7.4
* asyncpg version: 0.18.3
* aiocontextvars version: 0.2.2

* PostgreSQL version: 11

### Description

I have no way to capture an exception *and* rollback. I don't know what the intent was with raise_rollback() but it makes error handling a bit baffling.  I've never had to roll back a transaction with an exception before, so it's throwing me for a loop.

### What I Did

```
async def create_gathering_from_dict(gj):
    try:
       async with db.transaction() as tx:
           try:
               gm = Gathering(**gj)
               g = await gm.create()
               if g != None:
                   # h = await get_first(g)
                   hdata = generate_next_happening(g)
                   gh = get_scoped_gathering_json(g, Scope.CREATOR)
                   gh.happening = hdata
                   await tx.raise_commit()
               return gh
           except Exception as e:
               raise e # This is the error I want to pass to the caller
           finally:
               await tx.raise_rollback()
    except Exception as e:
       logger.error(e) # This line is never reached.
       raise e




async def create_gathering(gathering_json, user_id):
    gathering_json['public_id'] = generate(size=23)
    gathering_json['posted_by'] = "sir_greybeard"
    gathering_json['created_at'] = time.time()
    gathering_json['created_by_id'] = user_id
    try:
        g = await create_gathering_from_dict(gathering_json)
        if g != None:
            return g.to_struct()
    except Exception as e:
        logger.error(e) # This is never reached
        raise e

```
The return value of the function is None, but I want the function to exit with the error the database threw, and defer a rollback.

Depending on the error, it could be a user error or a system error, for instance a duplicate key exception. I can log the exception in the inner function, no problem, but the problem is the calling function never sees a raised exception. I've tried several things

**Comment by mikepc** [comment]
I think I figured out a workaround, seems super hacky but it works, so I'll just use it for now:

```
async def create_gathering_from_dict(gj):
       err = None
       async with db.transaction() as tx:
           try:
               gm = Gathering(**gj)
               g = await gm.create()
               if g != None:
                   # h = await get_first(g)
                   hdata = generate_next_happening(g)
                   gh = get_scoped_gathering_json(g, Scope.CREATOR)
                   gh.happening = hdata
               return gh
           except Exception as e:
               err = e
               await tx.raise_rollback()
       if err != None:
            raise err


```

**Comment by fantix** [comment]
1. You don't have to call `raise_commit()` or `raise_rollback()` to end a transaction started with `async with db.transaction():` - it is committed automatically when exiting the `async with` block, or rolled back if there is an exception.
2. `raise_commit()` and `raise_rollback()` are only used for convenience when you need to end the transaction early and skip the remaining code in the `async with` block.
3. Your first code didn't work because `raise_rollback()` in `finally` raised an internal exception which overwrote the one you "re-raised" (which doesn't make sense).
4. You could just:
```python
       try:
           async with db.transaction() as tx:
               ...
               return gh
       except Exception as e:
           logger.error(e)
           raise e
```
