### ISSUE TITLE
gino.exceptions.UninitializedError: Gino engine is not initialized.

### ISSUE THREAD

**Issue by dark0ghost** [fantix/gino#557]
this code https://pastebin.com/4KBtqG0h
traceback gino.exceptions.UninitializedError: Gino engine is not initialized.
how fix?

**Comment by mikekeda** [comment]
You are setting bind inside task function, so inside make_paste db_pg.bind could be not initialized.
Do you have an error inside make_paste?

**Comment by dark0ghost** [comment]
Ok,how use bind in func?

**Comment by mikekeda** [comment]
What framework are you using?
For Sanic you could set bind inside `@app.listener('after_server_start')`, check this - https://github.com/fantix/gino/blob/master/gino/ext/sanic.py#L96
There are also code for other frameworks - https://github.com/fantix/gino/tree/master/gino/ext

**Comment by dark0ghost** [comment]
Aiogram (tg bot)

**Comment by dark0ghost** [comment]
I ended up failing. I can not transfer bind from a file with a connection to the database to a file with a handler

**Comment by mikekeda** [comment]
try to add those line to your handler:
```
if not db_pg.bind:
    await db_pg.set_bind(help.POSTGRES)
```

**Comment by dark0ghost** [comment]
https://pastebin.com/sZLSTada traceback
