### ISSUE TITLE
How to get a number of updated rows?

### ISSUE THREAD

**Issue by vemikhaylov** [fantix/gino#558]
* GINO version: 0.8.3
* Python version: 3.7.3
* asyncpg version: 0.18.3
* PostgreSQL version: 11.3

### Description

Is there any in-built interface to get number of matched and updated rows for update request?  

### What I Did

I can see that gino.status() for it returns tuple, which first element is a status from a database ("UPDATE ...").
 
As in documentation:
```python
    status, result = await User.update.values(
        nickname='No.' + db.cast(User.id, db.Unicode),
    ).where(
        User.id > 10,
    ).gino.status()
    print(status)  # UPDATE 8
```

Certainly, I can parse this status to answer my question, however, is there more smooth way?

**Comment by fantix** [comment]
libpq provides a function to parse this string (see the git.io link here: https://github.com/fantix/gino/blob/7a1094a7b53ae3d4d1f4507ccfd15805888173b7/gino/engine.py#L342-L348), but GINO/asyncpg is not using libpq (while psycopg2 does). Before a similar feature is implemented in asyncpg or even GINO, I guess we'll have to write similar code to manually parse the status string.

**Comment by vemikhaylov** [comment]
Ok, thanks

**Comment by fantix** [comment]
Sure thing!
