### ISSUE TITLE
I want to know the gino equivalent for this particular sql query :- 

### ISSUE THREAD

**Issue by vasu343** [fantix/gino#563]
Sql query :- SELECT * from calvents c, json_array_elements(c.invitees) as emails where CAST(emails ->> 'email' as TEXT) = 'abc@gmail.com'

invitees is an array of json objects :- [{"name":"val1", "email":"val2"}, .....]

**Comment by vasu343** [comment]
Sql query :- SELECT  * from calvents c, json_array_elements(c.invitees) as emails where CAST(emails ->> 'email' as TEXT) = 'abc@gmail.com'

**Comment by fantix** [comment]
https://stackoverflow.com/questions/38751438
https://docs.sqlalchemy.org/en/13/dialects/postgresql.html?highlight=astext#sqlalchemy.dialects.postgresql.JSON

**Comment by vasu343** [comment]
Thanks for sharing the links. I had already seen the stackoverflow link before, but it is using session from the sqlalchemy orm which I can't use since I am using gino. So the same query won't work. Can you tell me what the gino equivalent of that sqlalchemy query is

**Comment by wwwjfy** [comment]
Let us know what you have tried and where you have trouble getting the result.
This is a SQLAlchemy question, rather than a Gino question; and there is not much difference between Query and raw expressions in SQLAlchemy given that there is no relationship in your query.
