### ISSUE TITLE
How to use loaders with subqueries

### ISSUE THREAD

**Issue by michaelkrukov** [fantix/gino#573]
I am trying to load User models from subquery (in order to use 'where', 'limit' and 'offset'). But I can't load User models from rows, because loader can't find model's columns.

```py
class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer(), primary_key=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._tags = set()

    @property
    def tags(self):
        return self._tags

    @tags.setter
    def add_tag(self, tag):
        self._tags.add(tag)

class Tag(db.Model):
    __tablename__ = 'tags'
    id = db.Column(db.Integer(), primary_key=True)

class UserXTag(db.Model):
    __tablename__ = 'users_x_tags'
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id'))
    tag_id = db.Column(db.Integer(), db.ForeignKey('tags.id'))

async def main():
    await db.set_bind('postgresql://...')

    sub_joined = User.outerjoin(UserXTag).outerjoin(Tag)
    sub_select = Select([User], None, from_obj=sub_joined)
    sub_grouped = sub_select.group_by(*User)
    sub_filtered = sub_grouped.having(func.count(Tag.id) > 0)
    
    # I forced to do this by Postgresql (?)
    # 'subquery in FROM must have an alias'
    sub_query = sub_filtered.alias('users')
    
    # I can do this to force expected columns, but I really don't need it (?)
    # sub_query = User.join(sub_query, User.id == SubUser.id)

    query = sub_query.outerjoin(UserXTag).outerjoin(Tag).select()

    print(query)

    loader = (User.distinct(User.id).load(add_tag=Tag.distinct(Tag.id)))

    users = await query.gino.load(loader).all()
    # sqlalchemy.exc.NoSuchColumnError: "Could not locate column in row for column 'users.id'"
```

The resulting SQL query is correct, but the loader `ModelLoader` can't use subquery's columns as no column has correct table (because a subquery is considered an entirely separate table, I guess).

```sql
SELECT users.id, users_x_tags.user_id, users_x_tags.tag_id, tags.id FROM (SELECT users.id AS id FROM users LEFT OUTER JOIN users_x_tags ON users.id = users_x_tags.user_id LEFT OUTER JOIN tags ON tags.id = users_x_tags.tag_id GROUP BY users.id HAVING count(tags.id) > $1) AS users LEFT OUTER JOIN users_x_tags ON id = users_x_tags.user_id LEFT OUTER JOIN tags ON tags.id = users_x_tags.tag_id
```

> "users" (as in model User) is a different table from "users" created throught "alias"

I used this code to check how row accessed (added in ModelLoader's `do_load` method):

```py
_id = self._distinct[0]
for k, v in row._keymap.items():
    print(k, '==', _id, k is _id)
    if isinstance(k, str):
        continue
    print(k.table == _id.table)
    print('---')

# Output:
# users.id == users.id False
# False
# ---
```

So, how do I change my code to use loaders to parse rows, received from subquery from the "users" table? Or should I be using an entirely different approach?

**Comment by wwwjfy** [comment]
You're right that the error here is because `User` and `users` are different model to SQLAlchemy or Gino even though they have the same definition.

Regardless if there are more optimal other ways for this specific logic, I see it's not an unusual case where we need to load a model from a subquery.

Let me try to add convenient classes/methods to make client code clean.

**Comment by QuadX23** [comment]
I have same eror when try load query with subquery:
 subquery = News.query.order_by(
        News.publish_date.desc()
    ).limit(limit).offset(offset).as_scalar().alias('news')
    query = subquery.outerjoin(User).outerjoin(Category).outerjoin(NewsTag).outerjoin(Tag).select()
    news_list = await query.gino.load(
        News.distinct(News.id).load(author=User, category=Category, tags=Tag.distinct(Tag.id))
    ).all()

**Comment by wwwjfy** [comment]
I tried to add a method to simplify the effort to get the Model instance in #585. Feel free to try and comment.
