### ISSUE TITLE
How do I Batch Update

### ISSUE THREAD

**Issue by nimwijetunga** [fantix/gino#575]
* GINO version: 0.8.3
* Python version: 3.6.6
* asyncpg version: 0.19.0
* PostgreSQL version: 11.5

I have the following model:
```
class ProviderHotel(db.Model):
  __bind_key__ = 'hotels'
  __tablename__ = 'provider_hotels'

  id = db.Column(db.Integer, primary_key=True)
  provider = db.Column(db.String)
  travolutionary_id = db.Column(db.String)
  hotel_id = db.Column(db.Integer)
  provider_hotel_id = db.Column(db.String)
...
```

I have the following python object:

```
obj = {
  '1': {
    'provider_hotel_id': 1,
   ...
 },
'2': {
    'provider_hotel_id': 2,
   ...
 },
'3': {
    'provider_hotel_id': 3,
   ...
 },
}
```

I would like to filter all the entries in the db which have `provider_hotel_id = obj.keys()` then update them by unpacking their respective `obj.value()`. I know this can be accomplished by first querying the db then updating each entry and then using `.apply()` command, but I am wondering if there is any way I can do a batch update as it is expensive to commit for each row updated (for large number of rows).

**Comment by wwwjfy** [comment]
This is more a PostgreSQL question, than a Gino or Python question.
From what I understand, what we can do to improve performance, in my preference order:

- Instead of querying and updating, this can be done using one query using `where`
- Put all updates in one transaction
- Create PostgreSQL functions and put the logic there, to save network cost

Depending on the nature of the business logic, more frequent commits may not be a bad thing, to avoid potential conflicts.

**Comment by nimwijetunga** [comment]
Thanks for the answer. So with my understanding with a where/update statement I am not able to get the current information for the row I'm updating, thus I'm not sure how to unpack the correct value associated with the key. Could you give an example of this query?

**Comment by wwwjfy** [comment]
I'm not clear about your requirement. Why do you need the current info to update the row? If the new values is based on the old values, it'll be quite easy right? like `UPDATE users SET v = v + 1`.
Otherwise, as I know, there is no direct way to update multiple rows in one statement.
There are still ways to hack around, but that'll depend on what you want to achieve.

**Comment by nimwijetunga** [comment]
In the example I placed above I am not updating a single value. I need to update multiple values for a single row. So I need to unpack the dictionary for a given key. The values to update vary from object to object. If I can't update multiple values how can i update using a transaction?

**Comment by wwwjfy** [comment]
By `batch update`, do you mean to update multiple properties of one row?
Let me try to give an example:

```python
from sqlalchemy import update
async with db.transaction() as t:
    for id_, prop in obj.items():
        q = (update(ProviderHotel).
                where(ProviderHotel.id == id_).
                values(provider_hotel_id=prop['provider_hotel_id'],
                       hotel_id=prop['hotel_id'],
                       others=prop['others']))
        await q.gino.all()
```

**Comment by nimwijetunga** [comment]
Thanks for the example this is actually what I’m doing right now. In my case id_ maps to exactly one row (like a primary key). Instead of committing one row at a time like above I’m wondering if I can update all rows then commit at the end. Like for example commuting at the end of your for loop

**Comment by wwwjfy** [comment]
By committing, if you mean commit in the transaction, it'll be done only once when exiting the transaction block, but each statement it'll talk to database, i.e. network communication.
As mentioned, there are other ways to do it, but I'd like to know what's the problem with this and what you want to improve.

**Comment by nimwijetunga** [comment]
I see the main thing I want to improve is speed. Im updating around 10000 rows at once and need a way to speed up the process. The `obj` dict has around 10000 entries which needs to be updated

**Comment by wwwjfy** [comment]
I'd do profiling first, to find out the bottleneck.
Usually updating 10K rows should not be slow. I'd check cpu/memory usage, check db index usage, using EXPLAIN to see the plan. I don't see batch update itself can speed it up drastically, as it can only save round trip time and db still needs to update rows one by one.

**Comment by wwwjfy** [comment]
Closing as it's not really a Gino question. Being a simple "ORM", if you can find out the raw SQL statement, or SQLAlchemy statements, Gino can usually provide an equivalence.
