### ISSUE TITLE
Database autogenerate migrations

### ISSUE THREAD

**Issue by nsiregar** [fantix/gino#579]
* GINO version: 0.8.3
* Python version: 3.7.5
* asyncpg version: 0.19.0
* aiocontextvars version: 0.2.2
* PostgreSQL version: 10.10

### Description
How to make model's `__tablename__` is autogenerated? 
I've tried to using `gino.declarative.declared_attr` to automatically generate `__tablename__` attribute for model, but got error

`KeyError: '<function BaseModel.__tablename__ at 0x7f21defb7950>'`

### What I Did
I tried to structuring applications with `starlette` here https://github.com/nsiregar/letsgo but unable to autogenerate `__tablename__`

**Comment by mikekeda** [comment]
Why do you need to autogenerate __tablename__? What you trying to do?

**Comment by wwwjfy** [comment]
Currently `declared_attr` doesn't support `__tablename__`. You could probably achieve that by inheriting metaclass and implementing `__getattribute__`, but yeah as @mikekeda asked, what's your use case? This is an important attribute for a Table class, to be distinguished between a parent class or mixin, etc.

**Comment by nsiregar** [comment]
I was trying to implement singular - plural for model and it's table. By automatically generate plural table name, it will make easier to find which model related to which table.

**Comment by wwwjfy** [comment]
Fair enough. It should not be hard. I should be able to add this soon.

**Comment by nsiregar** [comment]
that will be great, waiting for new release
