### ISSUE TITLE
Sanic extension using deprecated request.pop() method

### ISSUE THREAD

**Issue by sjsadowski** [fantix/gino#581]
One of our users reported this issue here: https://github.com/huge-success/sanic/issues/1711

Issue is found here:
https://github.com/fantix/gino/blob/2c233e9fcf80637ef24f9d16d8652d27d14bddf7/gino/ext/sanic.py#L91

**Comment by harshanarayana** [comment]
Same as #569

**Comment by wwwjfy** [comment]
I think this is not the best way that Gino maintains the compatibility of different versions of Sanic, which may ends up with a lot of if/else. I may fix this for this time, but if this happens too often, we'll need another way.
