### ISSUE TITLE
How to define model classes in multiple files?

### ISSUE THREAD

**Issue by atipi** [fantix/gino#586]
* GINO version: 0.8.3
* Python version: 3.7.4
* asyncpg version: 0.19.0
* aiocontextvars version: 0.2.2
* PostgreSQL version: 11.4

### Description

I would like to create multiple files for each model classes. For example:
- models/user.py -> Keep User model class
- models/area.py -> Keep Area model class
- database.py -> Central place to manage database.
- app.py -> Main file to start database and create tables etc.

Is it possible to do without putting all models in one file? And how? 

### What I Did

I have defined this code in database.py
```
from gino import Gino


class Database:
    def __init__(self, database=None):
        if database:
            self.db = database
        else:
            self.db = Gino()

    def get_db(self):
        return self.db

    def connect_db(self):
        return self.db.set_bind('postgresql://localhost/gino')

    def close_db(self):
        return self.db.pop_bind().close()

```

Then in for example user.py
```
from app import db


class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer(), primary_key=True)
    name_en = db.Column(db.Unicode())
```

Finally in app.py
```
import asyncio
from gino import Gino

from database import Database

database = Database(database=Gino())
db = database.get_db()


async def main():
    await database.connect_db()
    print('Connect to DB')

    await db.gino.create_all()
    print('Create tables')

    # further code goes here

    await database.close_db()
    print('Close DB')

asyncio.get_event_loop().run_until_complete(main())
```

**Comment by wwwjfy** [comment]
Yes, it's possible. The way it works is that the metaclass `db.Model` will register the models when defining the classes. So, you only need to import the files declaring the classes because it's used.

**Comment by atipi** [comment]
Could you give an example of working solution? I tried and can't get tables created.

**Comment by atipi** [comment]
I figured it out how to get it to work! In the root file I need to import all model classes even I don't use them yet otherwise tables won't be created.

**Comment by wwwjfy** [comment]
sorry missed it yesterday. And yes, that's what I mean, you only need to import the files to let the metaclass be aware of these models.
