### ISSUE TITLE
[Question] How to use sslmode=True with Sanic

### ISSUE THREAD

**Issue by snguyenthanh** [fantix/gino#587]
* GINO version: 0.8.3
* Python version: 3.7.3
* asyncpg version: 0.19.0
* aiocontextvars version: 0.2.2
* PostgreSQL version: 11
* Sanic version: 19.6.3

How can I set `sslmode=True` for `Gino` using with `Sanic` ?

Using raw `Gino` - `db.set_bind(<url>, ssl=True)` seems to be the answer, but I don't know how to config it when it is used with `Sanic`.

**Comment by wwwjfy** [comment]
set it in the config `DB_SSL` along with other parameters like `DB_HOST`

**Comment by snguyenthanh** [comment]
> set it in the config `DB_SSL` along with other parameters like `DB_HOST`

I see. I didn't know `DB_SSL` exists, so I ended up using `DB_DSN` that has the whole connection string.
