### ISSUE TITLE
Publish new version on pypi

### ISSUE THREAD

**Issue by RmStorm** [fantix/gino#589]
Hi I just ran into and made a fix for #579. Then I thought I would try to push it upstream and found that it is already fixed in the repo! Is it possible to push more often to pypi?

Also actually running the tests was a lot harder than expected. I upgraded the docs a little to clarify how to run a postgres database with ssl in a docker container so that all tests succeed.

**Comment by leosussan** [comment]
+1 - lots of useful stuff pushed in the last couple of months that haven't been pushed to PyPi yet!

**Comment by fantix** [comment]
Oh yes, I should've done that weeks ago - sry about that! I was trying Poetry and got distracted after that. Let's still do a normal release first.

**Comment by wwwjfy** [comment]
Thanks! Pushed 0.8.4. It should be available soon.

**Comment by wwwjfy** [comment]
@fantix I tried a few times, but Travis seems not to be able to publish it. Please take a look.

**Comment by fantix** [comment]
on it

**Comment by QuadX23** [comment]
Please push 0.8.4 to PyPI

**Comment by fantix** [comment]
done

**Comment by wwwjfy** [comment]
@fantix Is the issue rst format? lol. my bad. 🤦‍♂️

**Comment by fantix** [comment]
@wwwjfy not sure if that's the only issue but yeah, no worries ;)
