### ISSUE TITLE
Please add a couple of words in README about how to migrate from pure sqlalchemy to GINO

### ISSUE THREAD

**Issue by konstunn** [fantix/gino#615]
Please add a couple of words in README about how to migrate from pure sqlalchemy to GINO

**Comment by konstunn** [comment]
Ok, I have found some information in this case in the documentation http://gino.fantix.pro/en/latest/schema.html

**Comment by fantix** [comment]
Right, I'll make that a more explicit how-to guide in the new documentation. Thanks for the notes!
