### ISSUE TITLE
Optionally depend on aiocontextvars

### ISSUE THREAD

**Issue by fantix** [fantix/gino#89]
This topic started in #84. We'll decide here:
 * Whether to rename the locals API as demonstrated in 820990c, or
 * separate `local.py` into a new Python package

Update:

New package aiocontextvars is created, task here is to make use of it as an optional dependency, while trying not to break old code.

**Comment by smagafurov** [comment]
IMHO "separate local.py into a new Python package" is a right way.

**Comment by fantix** [comment]
https://github.com/fantix/aiocontextvars
